/**
 * Behavior and rule tools.
 */
import { assertRevision, requireProject, toolError } from '../project-authoring';
import { applyBehaviorDslToComponents, hasBehaviorDslErrors } from '../../../../shared/formflow-core/behaviorDsl';
import { formContext, lintRuleCode, readRuleReference, runRuleSandbox } from '../rule-agent';
import { behaviorListInputSchema, behaviorRuleSchema } from '../tool-shared';
import type { RegisterFn, ToolHelpers } from './types';

function projectId(input: Record<string, any>, context: { projectId?: string }) { return String(input.projectId || context.projectId || ''); }
function findById(items: any[], id: string, code: string) { const item = items.find((entry) => entry.id === id); if (!item) throw toolError(code, `${id} 不存在`); return item; }
function upsert(items: any[], item: any) { const index = items.findIndex((entry) => entry.id === item.id); if (index >= 0) items[index] = item; else items.push(item); return item; }
function remove(items: any[], id: string) { const index = items.findIndex((entry) => entry.id === id); if (index < 0) return false; items.splice(index, 1); return true; }

export function registerBehaviorTools(register: RegisterFn, h: ToolHelpers) {
  register({ name: 'behavior.list', title: '行为列表', description: '按 global/sheet/form 作用域列出行为；form 必须传 formId，sheet 必须传 tableId 和 sheetName。', inputSchema: behaviorListInputSchema, risk: 'read', requiredAccess: 'view', handler: (input, context) => {
    const project = requireProject(projectId(input, context));
    if (input.scope === 'global') return project.globalBehaviors || [];
    if (input.scope === 'form') { if (!input.formId) throw toolError('REQUIRED_ARGUMENT', 'scope=form 时缺少参数 formId', 'formId'); return findById(project.forms || [], input.formId, 'FORM_NOT_FOUND').behaviors || []; }
    if (input.scope === 'sheet') { if (!input.tableId) throw toolError('REQUIRED_ARGUMENT', 'scope=sheet 时缺少参数 tableId', 'tableId'); if (!input.sheetName) throw toolError('REQUIRED_ARGUMENT', 'scope=sheet 时缺少参数 sheetName', 'sheetName'); return (project.sheetBehaviors || []).find((item: any) => item.tableId === input.tableId && item.sheetName === input.sheetName)?.behaviors || []; }
    throw toolError('INVALID_ARGUMENT', 'scope 必须是 global、sheet 或 form', 'scope');
  } });
  register({ name: 'behavior.upsert', title: '保存结构化行为', description: '在 global/sheet/form 作用域保存完整 Trigger/Condition/Action 行为。表单字段联动优先使用 rule_code.update；禁止空 expression 占位。', inputSchema: h.schema(['projectId', 'scope', 'behavior', 'baseRevision', 'idempotencyKey'], { projectId: h.string, scope: { type: 'string', enum: ['global', 'sheet', 'form'] }, behavior: behaviorRuleSchema, baseRevision: h.string, idempotencyKey: h.string, formId: h.string, tableId: h.string, sheetName: h.string }), risk: 'write', requiredAccess: 'edit', handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); let collection: any[]; if (input.scope === 'global') collection = project.globalBehaviors ||= []; else if (input.scope === 'form') collection = findById(project.forms || [], input.formId, 'FORM_NOT_FOUND').behaviors ||= []; else { let entry = (project.sheetBehaviors ||= []).find((item: any) => item.tableId === input.tableId && item.sheetName === input.sheetName); if (!entry) { entry = { tableId: input.tableId, sheetName: input.sheetName, behaviors: [], updatedAt: new Date().toISOString() }; project.sheetBehaviors.push(entry); } collection = entry.behaviors; } upsert(collection, { enabled: true, priority: 20, conditions: [], ...input.behavior, updatedAt: new Date().toISOString() }); project.config.updatedAt = new Date().toISOString(); return h.commitProject(project); } });
  register({ name: 'behavior.delete', title: '删除行为', description: '从指定作用域删除行为。', inputSchema: h.schema(['projectId', 'scope', 'id', 'baseRevision', 'idempotencyKey'], { projectId: h.string, scope: { type: 'string', enum: ['global', 'sheet', 'form'] }, id: h.string, baseRevision: h.string, idempotencyKey: h.string, formId: h.string, tableId: h.string, sheetName: h.string, confirmationToken: h.string }), risk: 'destructive', requiredAccess: 'edit', impact: (input) => ({ scope: input.scope, behaviorId: input.id }), handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); let collection: any[] = project.globalBehaviors || []; if (input.scope === 'form') collection = findById(project.forms || [], input.formId, 'FORM_NOT_FOUND').behaviors || []; else if (input.scope === 'sheet') collection = (project.sheetBehaviors || []).find((item: any) => item.tableId === input.tableId && item.sheetName === input.sheetName)?.behaviors || []; remove(collection, input.id); project.config.updatedAt = new Date().toISOString(); return h.commitProject(project); } });
  register({ name: 'rule_code.update', title: '更新表单规则', description: '校验 Behavior Rule DSL，通过后写入表单并编译为可执行的控件联动。', inputSchema: h.schema(['projectId', 'formId', 'code', 'baseRevision', 'idempotencyKey'], { projectId: h.string, formId: h.string, code: h.string, baseRevision: h.string, idempotencyKey: h.string }), risk: 'write', requiredAccess: 'edit', handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const form = findById(project.forms || [], input.formId, 'FORM_NOT_FOUND'); const compilation = lintRuleCode(project.config.id, form.id, String(input.code || '')); if (hasBehaviorDslErrors(compilation)) throw toolError('RULE_SYNTAX_INVALID', '规则语法或引用校验失败', 'code', compilation.diagnostics); const applied = applyBehaviorDslToComponents(form.design?.components || [], String(input.code || ''), form.design?.formWindow); if (applied.unapplied.length) throw toolError('RULE_APPLY_FAILED', applied.unapplied[0], 'code', applied.unapplied); const now = new Date().toISOString(); form.ruleCode = String(input.code || ''); form.design.components = applied.components; form.design.formWindow = applied.formWindow || form.design.formWindow; form.design.updatedAt = now; form.updatedAt = now; project.config.updatedAt = now; return h.commitProject(project); } });
  register({ name: 'rule_syntax.lint', title: '规则语法检查', description: '检查 FormFlow 受控规则 DSL。', inputSchema: h.schema(['formId', 'code'], { projectId: h.string, formId: h.string, code: h.string }), risk: 'read', requiredAccess: 'view', handler: (input, context) => lintRuleCode(projectId(input, context), input.formId, input.code) });
  register({ name: 'rule_test.run', title: '规则隔离测试', description: '在隔离沙箱运行规则测试。', inputSchema: h.schema(['formId', 'code'], { projectId: h.string, formId: h.string, code: h.string }), risk: 'read', requiredAccess: 'view', handler: (input, context) => runRuleSandbox(projectId(input, context), input.formId, input.code) });
  register({ name: 'rule_reference.search', title: '规则参考搜索', description: '搜索权威规则语法参考。', inputSchema: h.schema(['query'], { query: h.string }), risk: 'read', handler: (input) => readRuleReference(input.query) });
}
