/**
 * Data source, sheet, row, and relation tools.
 */
import { assertRevision, batchProjectRows, fullSourceRows,
  queryProjectRows, requireProject, serializeTableSource, tableFromInput, toolError } from '../project-authoring';
import { applyDataRowsTransaction, queryRelationRows, suggestDataRelations, validateRelation, type DataRelation } from '../template';
import { dataSourceConfigSchema, dataRowUpdateSchema } from '../tool-shared';
import type { RegisterFn, ToolHelpers } from './types';

export function registerDataTools(register: RegisterFn, h: ToolHelpers) {
  const { projectId } = h;
  // Data source CRUD
  register({ name: 'data_source.list', title: '数据源列表', description: '列出项目数据源。', inputSchema: h.schema(['projectId'], { projectId: h.string }), risk: 'read', requiredAccess: 'view', examples: [{ summary: '列出项目数据源', arguments: { projectId: 'device_mgmt' } }], handler: (input, context) => requireProject(projectId(input, context)).srcTable || [] });
  register({ name: 'data_source.get', title: '读取数据源', description: '读取数据源及 Sheet 元数据。id 是 data_source.list 返回的表 id。', inputSchema: h.schema(['projectId', 'id'], { projectId: h.string, id: h.string }), risk: 'read', requiredAccess: 'view', examples: [{ summary: '读取 device 表结构（含列与主键）', arguments: { projectId: 'device_mgmt', id: 'device' } }], handler: (input, context) => { const items = requireProject(projectId(input, context)).srcTable || []; const item = items.find((e: any) => e.id === input.id); if (!item) throw toolError('TABLE_NOT_FOUND', `${input.id} 不存在`); return item; } });
  for (const [name, title] of [['data_source.create', '创建数据表'], ['data_source.import', '导入数据源']] as const) register({ name, title, description: '从上传 fileId、业务数据行 rows、CSV 或 config.columns 创建数据源。rows 中每个对象代表一条业务记录，不是字段定义；空表使用 config.columns。config.keyFields 必须位于 config 顶层并匹配 rows 键或 columns.name。', inputSchema: h.schema(['projectId', 'id', 'baseRevision', 'idempotencyKey'], { projectId: h.string, id: h.string, baseRevision: h.string, idempotencyKey: h.string, fileId: h.string, rows: { type: 'array', items: { type: 'object', additionalProperties: true }, description: '业务记录数组；字段名作为列名。不要传 fieldId/title/type 字段定义。' }, csv: h.string, sheetName: h.string, config: dataSourceConfigSchema }), risk: 'write', requiredAccess: 'edit', examples: [{ summary: '创建空表（config.columns 定义列与主键）', arguments: { projectId: 'device_mgmt', id: 'device', config: { columns: [{ name: '编号', type: 'string' }, { name: '名称', type: 'string' }, { name: '类型', type: 'enum', enum: ['机床', '泵', '阀门'] }, { name: '评分', type: 'number' }], keyFields: ['编号'] } }, success: { revision: '…' }, errors: [{ code: 'TABLE_EXISTS', message: '数据表已存在' }, { code: 'DATA_KEY_REQUIRED', message: '可编辑表必须配置 config.keyFields' }] }, { summary: '用 rows 建表并导入业务数据', arguments: { projectId: 'device_mgmt', id: 'device', rows: [{ 编号: 'D-001', 名称: '机床A', 类型: '机床', 评分: 88 }], config: { keyFields: ['编号'] } }, success: { revision: '…' }, errors: [{ code: 'TABLE_EXISTS', message: '数据表已存在' }] }], handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); if ((project.srcTable || []).some((item: any) => item.id === input.id)) throw toolError('TABLE_EXISTS', `数据表 ${input.id} 已存在`); const built = tableFromInput({ ...input, tenantId: context.tenantId }); project.srcTable.push(built.table); project.config.updatedAt = new Date().toISOString(); return h.commitProject(project, built.sourceFiles); } });
  register({ name: 'data_source.update', title: '更新数据源', description: '更新数据源显示元信息；原表和 Sheet 结构只能由专用数据接口修改。', inputSchema: h.schema(['projectId', 'id', 'baseRevision', 'idempotencyKey', 'patch'], { projectId: h.string, id: h.string, baseRevision: h.string, idempotencyKey: h.string, patch: h.object }), risk: 'write', requiredAccess: 'edit', examples: [{ summary: '给数据源加备注', arguments: { projectId: 'device_mgmt', id: 'device', baseRevision: '<revision>', idempotencyKey: 'upd-1', patch: { remark: '设备台账' } } }], handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const table = (project.srcTable || []).find((item: any) => item.id === input.id); if (!table) throw toolError('TABLE_NOT_FOUND', `${input.id} 不存在`); const protectedFields = ['fileName', 'fileType', 'fileSize', 'dataHash', 'uploadedAt', 'sheets', 'preview', 'rows']; const invalid = protectedFields.find((field) => input.patch?.[field] !== undefined); if (invalid) throw toolError('PROTECTED_DATA_FIELD', `${invalid} 只能由项目数据接口修改`, `patch.${invalid}`); Object.assign(table, input.patch, { id: table.id }); project.config.updatedAt = new Date().toISOString(); return h.commitProject(project); } });
  register({ name: 'data_source.delete', title: '删除数据源', description: '删除数据源；有引用时必须显式 cascade。', inputSchema: h.schema(['projectId', 'id', 'baseRevision', 'idempotencyKey'], { projectId: h.string, id: h.string, baseRevision: h.string, idempotencyKey: h.string, cascade: h.boolean, confirmationToken: h.string }), risk: 'destructive', requiredAccess: 'edit', impact: (input) => ({ dataSourceId: input.id, cascade: !!input.cascade }), examples: [{ summary: '删除数据源（需确认）', arguments: { projectId: 'device_mgmt', id: 'device', baseRevision: '<revision>', idempotencyKey: 'del-1' } }], handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const refs = (project.forms || []).filter((form: any) => JSON.stringify(form).includes(input.id)); if (refs.length && !input.cascade) throw toolError('RESOURCE_REFERENCED', '数据源仍被表单引用', 'id', { forms: refs.map((item: any) => item.id) }); const idx = (project.srcTable || []).findIndex((item: any) => item.id === input.id); if (idx >= 0) project.srcTable.splice(idx, 1); if (input.cascade) project.forms = (project.forms || []).filter((form: any) => !JSON.stringify(form).includes(input.id)); project.sheetBehaviors = (project.sheetBehaviors || []).filter((item: any) => item.tableId !== input.id); project.config.updatedAt = new Date().toISOString(); return h.commitProject(project); } });

  // Sheet configuration
  register({ name: 'data_sheet.get', title: '读取 Sheet', description: '读取 Sheet 元数据和行版本。', inputSchema: h.schema(['projectId', 'tableId', 'sheetName'], { projectId: h.string, tableId: h.string, sheetName: h.string }), risk: 'read', requiredAccess: 'view', examples: [{ summary: '读取 device 表的 Sheet1 配置', arguments: { projectId: 'device_mgmt', tableId: 'device', sheetName: 'Sheet1' } }], handler: (input, context) => { const table = (requireProject(projectId(input, context)).srcTable || []).find((item: any) => item.id === input.tableId); if (!table) throw toolError('TABLE_NOT_FOUND', '数据表不存在'); const sheet = (table.sheets || []).find((item: any) => item.name === input.sheetName); if (!sheet) throw toolError('SHEET_NOT_FOUND', 'Sheet 不存在'); return sheet; } });
  register({ name: 'data_sheet.configure', title: '配置 Sheet', description: '设置主键、只读、冻结、筛选和排序。tableId 是 data_source.list/get 返回的数据表 id，sheetName 是该表的 Sheet 名；可编辑表必须配置 config.keyFields 主键。', inputSchema: h.schema(['projectId', 'tableId', 'sheetName', 'baseRevision', 'idempotencyKey', 'config'], { projectId: h.string, tableId: h.string, sheetName: h.string, baseRevision: h.string, idempotencyKey: h.string, config: dataSourceConfigSchema }), risk: 'write', requiredAccess: 'edit', examples: [{ summary: '把主键配置为编号并保持可编辑', arguments: { projectId: 'device_mgmt', tableId: 'device', sheetName: 'Sheet1', baseRevision: '<revision>', idempotencyKey: 'cfg-1', config: { keyFields: ['编号'], readOnly: false, filterEnabled: true } }, success: { revision: '…' }, errors: [{ code: 'TABLE_NOT_FOUND', message: '数据表不存在（tableId 错误）' }, { code: 'SHEET_NOT_FOUND', message: 'Sheet 不存在' }] }], handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const table = (project.srcTable || []).find((item: any) => item.id === input.tableId); if (!table) throw toolError('TABLE_NOT_FOUND', '数据表不存在'); const sheet = (table.sheets || []).find((item: any) => item.name === input.sheetName); if (!sheet) throw toolError('SHEET_NOT_FOUND', 'Sheet 不存在'); sheet.config = { ...sheet.config, ...input.config, id: sheet.config?.id || sheet.name, tableName: sheet.name }; project.config.updatedAt = new Date().toISOString(); return h.commitProject(project); } });

  // Key validation
  register({ name: 'data_keys.validate', title: '校验主键', description: '校验指定或已配置的组合主键。', inputSchema: h.schema(['projectId', 'tableId', 'sheetName'], { projectId: h.string, tableId: h.string, sheetName: h.string, keyFields: { type: 'array' } }), risk: 'read', requiredAccess: 'view', examples: [{ summary: '校验编号主键无空值/重复', arguments: { projectId: 'device_mgmt', tableId: 'device', sheetName: 'Sheet1', keyFields: ['编号'] } }], handler: (input, context) => { const project = requireProject(projectId(input, context)); const table = (project.srcTable || []).find((item: any) => item.id === input.tableId); if (!table) throw toolError('TABLE_NOT_FOUND', '数据表不存在'); const sheet = (table.sheets || []).find((item: any) => item.name === input.sheetName); if (!sheet) throw toolError('SHEET_NOT_FOUND', 'Sheet 不存在'); const keys = input.keyFields || sheet.config?.keyFields || []; const seen = new Set(); const errors: any[] = []; fullSourceRows(project, table, sheet).forEach((row: any, index: number) => { const values = keys.map((key: string) => row[key]); const hash = JSON.stringify(values); if (values.some((value: any) => value === '' || value == null)) errors.push({ index, code: 'EMPTY_KEY' }); else if (seen.has(hash)) errors.push({ index, code: 'DUPLICATE_KEY', values }); seen.add(hash); }); return { valid: errors.length === 0, keyFields: keys, errors }; } });

  // Row operations
  register({ name: 'data_rows.query', title: '查询数据行', description: '分页搜索、筛选、排序并返回稳定 rowKey。', inputSchema: h.schema(['projectId', 'tableId', 'sheetName'], { projectId: h.string, tableId: h.string, sheetName: h.string, page: { type: 'number', minimum: 1 }, pageSize: { type: 'number', minimum: 1, maximum: 500 }, search: h.string, keySearch: { type: 'object', additionalProperties: true }, sortModel: { type: 'array' }, filterModel: h.object }), risk: 'read', requiredAccess: 'view', examples: [{ summary: '分页查询数据行', arguments: { projectId: 'device_mgmt', tableId: 'device', sheetName: 'Sheet1', page: 1, pageSize: 20 } }], handler: (input, context) => queryProjectRows(requireProject(projectId(input, context)), input) });
  register({ name: 'data_rows.batch', title: '批量写回数据', description: '按稳定 rowKey 原子应用新增、更新和删除；单次最多 1000 个变更。', inputSchema: h.schema(['projectId', 'tableId', 'sheetName', 'baseRevision', 'idempotencyKey'], { projectId: h.string, tableId: h.string, sheetName: h.string, baseRevision: h.string, baseVersion: h.string, idempotencyKey: h.string, adds: { type: 'array', items: { type: 'object', additionalProperties: true }, description: '新增业务记录。可直接传业务记录 {列名:值}（服务端按主键自动生成 rowKey），或 {rowKey:"key:<主键值>", changes:{列名:值}}。' }, updates: { type: 'array', items: dataRowUpdateSchema }, deletes: { type: 'array', items: h.string }, confirmationToken: h.string }), risk: 'write', requiredAccess: 'edit', confirmWhen: (input) => Array.isArray(input.deletes) && input.deletes.length > 0, impact: (input) => ({ deletes: input.deletes?.length || 0, tableId: input.tableId, sheetName: input.sheetName }), examples: [
    { summary: '新增 2 行业务记录（adds 直接写记录）', arguments: { projectId: 'device_mgmt', tableId: 'device', sheetName: 'Sheet1', baseRevision: '<revision>', idempotencyKey: 'rows-1', adds: [{ 编号: 'D-001', 名称: '机床A', 类型: '机床', 状态: '正常', 评分: 88 }, { 编号: 'D-002', 名称: '泵B', 类型: '泵', 状态: '待检', 评分: 52 }] }, success: { total: 8, dataVersion: '…', applied: { adds: 2, updates: 0, deletes: 0 } }, errors: [{ code: 'DATA_KEY_VALUE_EMPTY', message: '新增行主键字段为空' }, { code: 'DATA_VERSION_CONFLICT', message: '数据已被修改，需重新读取 baseVersion' }] },
    { summary: '按 rowKey 更新一行', arguments: { projectId: 'device_mgmt', tableId: 'device', sheetName: 'Sheet1', baseRevision: '<revision>', idempotencyKey: 'rows-2', updates: [{ rowKey: 'key:D-001', changes: { 评分: 95 } }] }, success: { total: 6, dataVersion: '…', applied: { adds: 0, updates: 1, deletes: 0 } }, errors: [{ code: 'DATA_KEY_VALUE_EMPTY', message: 'rowKey 对应的记录不存在' }] },
  ], handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const result = batchProjectRows(project, input); project.config.updatedAt = new Date().toISOString(); const committed = h.commitProject(project, serializeTableSource(project, input.tableId, input.sheetName)); return { ...result, revision: committed.revision }; } });
  register({ name: 'data_rows.transaction', title: '跨表原子写回', description: '在项目副本中预检并应用多个 Sheet 变更，全部成功后一次提交；支持事务内生成键引用。', inputSchema: h.schema(['projectId', 'baseRevision', 'idempotencyKey', 'operations'], { projectId: h.string, baseRevision: h.string, idempotencyKey: h.string, operations: { type: 'array', items: { type: 'object', additionalProperties: true } }, confirmationToken: h.string }), risk: 'write', requiredAccess: 'edit', confirmWhen: (input) => (input.operations || []).some((item: any) => Array.isArray(item.deletes) && item.deletes.length > 0), impact: (input) => ({ tables: (input.operations || []).map((item: any) => `${item.tableId}/${item.sheetName}`), changes: (input.operations || []).reduce((total: number, item: any) => total + (item.adds?.length || 0) + (item.updates?.length || 0) + (item.deletes?.length || 0), 0), deletes: (input.operations || []).reduce((total: number, item: any) => total + (item.deletes?.length || 0), 0) }), examples: [{ summary: '跨表原子写回', arguments: { projectId: 'device_mgmt', baseRevision: '<revision>', idempotencyKey: 'tx-1', operations: [{ tableId: 'device', sheetName: 'Sheet1', adds: [{ 编号: 'D-003', 名称: '阀门C', 评分: 60 }] }] } }], handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const result = applyDataRowsTransaction(project, input.operations || []); const sources = (input.operations || []).flatMap((item: any) => serializeTableSource(result.project, item.tableId, item.sheetName)); project.config.updatedAt = new Date().toISOString(); const committed = h.commitProject(result.project, sources); return { applied: result.applied, totalChanges: result.totalChanges, revision: committed.revision }; } });

  // Data relations
  register({ name: 'data_relation.list', title: '数据关系列表', description: '列出项目中声明的等值数据关系。', inputSchema: h.schema(['projectId'], { projectId: h.string }), risk: 'read', requiredAccess: 'view', examples: [{ summary: '列出项目关系', arguments: { projectId: 'device_mgmt' } }], handler: (input, context) => requireProject(projectId(input, context)).relations || [] });
  register({ name: 'data_relation.suggest', title: '建议数据关系', description: '按字段名称、类型、主键和样本值重合度生成可审计的关系建议，不自动写入。', inputSchema: h.schema(['projectId'], { projectId: h.string }), risk: 'read', requiredAccess: 'view', examples: [{ summary: '生成关系建议', arguments: { projectId: 'device_mgmt' } }], handler: (input, context) => suggestDataRelations(requireProject(projectId(input, context))) });
  register({ name: 'data_relation.validate', title: '校验数据关系', description: '校验关系两侧表、字段、数量和类型兼容性。', inputSchema: h.schema(['projectId', 'relation'], { projectId: h.string, relation: h.object }), risk: 'read', requiredAccess: 'view', examples: [{ summary: '校验一个关系定义', arguments: { projectId: 'device_mgmt', relation: { id: 'r1', name: '设备-日志', left: { tableId: 'device', sheetName: 'Sheet1', fields: ['编号'] }, right: { tableId: 'log', sheetName: 'Sheet1', fields: ['device_id'] }, cardinality: 'one-to-many' } } }], handler: (input, context) => validateRelation(requireProject(projectId(input, context)), input.relation as DataRelation) });
  register({ name: 'data_relation.upsert', title: '保存数据关系', description: '新增或更新正式数据关系；写入前执行完整校验。', inputSchema: h.schema(['projectId', 'baseRevision', 'idempotencyKey', 'relation'], { projectId: h.string, baseRevision: h.string, idempotencyKey: h.string, relation: h.object }), risk: 'write', requiredAccess: 'edit', examples: [{ summary: '保存一对一关系', arguments: { projectId: 'device_mgmt', baseRevision: '<revision>', idempotencyKey: 'rel-1', relation: { id: 'device_owner', name: '设备-负责人', left: { tableId: 'device', sheetName: 'Sheet1', fields: ['编号'] }, right: { tableId: 'owner', sheetName: 'Sheet1', fields: ['device_id'] }, cardinality: 'one-to-one' } } }], handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const relation = input.relation as DataRelation; if (!relation?.id) throw toolError('REQUIRED_ARGUMENT', '关系必须包含 id', 'relation.id'); const report = validateRelation(project, relation); if (!report.valid) throw toolError('RELATION_INVALID', '关系定义无效', 'relation', report); project.relations ||= []; const idx = project.relations.findIndex((item: any) => item.id === relation.id); if (idx >= 0) project.relations[idx] = relation; else project.relations.push(relation); project.config.updatedAt = new Date().toISOString(); const committed = h.commitProject(project); return { relation, validation: report, revision: committed.revision }; } });
  register({ name: 'data_relation.delete', title: '删除数据关系', description: '删除关系定义；被模板实例引用时需显式 cascade。', inputSchema: h.schema(['projectId', 'id', 'baseRevision', 'idempotencyKey'], { projectId: h.string, id: h.string, baseRevision: h.string, idempotencyKey: h.string, cascade: h.boolean, confirmationToken: h.string }), risk: 'destructive', requiredAccess: 'edit', impact: (input) => ({ relationId: input.id, cascade: !!input.cascade }), examples: [{ summary: '删除关系（需确认）', arguments: { projectId: 'device_mgmt', id: 'device_owner', baseRevision: '<revision>', idempotencyKey: 'rel-del-1' } }], handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const refs = (project.templateInstances || []).filter((item: any) => item.selection?.relationIds?.includes(input.id) || item.parameters?.relationId === input.id); if (refs.length && !input.cascade) throw toolError('RESOURCE_REFERENCED', '关系仍被模板实例引用', 'id', { templateInstances: refs.map((item: any) => item.id) }); project.relations = (project.relations || []).filter((item: any) => item.id !== input.id); if (input.cascade) project.templateInstances = (project.templateInstances || []).filter((item: any) => !refs.includes(item)); project.config.updatedAt = new Date().toISOString(); const committed = h.commitProject(project); return { deleted: true, revision: committed.revision }; } });
  register({ name: 'data_relation.query', title: '关联查询', description: '按已声明关系分页、筛选和排序，保留源主键；exportAll 可返回至多一万条导出数据。', inputSchema: h.schema(['projectId', 'relationId'], { projectId: h.string, relationId: h.string, joinType: { type: 'string', enum: ['inner', 'left'] }, page: { type: 'number' }, pageSize: { type: 'number' }, search: h.string, sortModel: { type: 'array' }, filterModel: h.object, exportAll: h.boolean }), risk: 'read', requiredAccess: 'view', examples: [{ summary: '按关系联查（左连接）', arguments: { projectId: 'device_mgmt', relationId: 'device_owner', joinType: 'left', page: 1, pageSize: 20 } }], handler: (input, context) => queryRelationRows(requireProject(projectId(input, context)), input as any) });
}
