/**
 * Data source, sheet, row, and relation tools.
 */
import { assertRevision, batchProjectRows, fullSourceRows,
  queryProjectRows, requireProject, serializeTableSource, tableFromInput, toolError } from '../project-authoring';
import { applyDataRowsTransaction, queryRelationRows, suggestDataRelations, validateRelation, type DataRelation } from '../template';
import { dataSourceConfigSchema, dataRowUpdateSchema } from '../tool-shared';
import type { RegisterFn, ToolHelpers } from './types';

export function registerDataTools(register: RegisterFn, h: ToolHelpers) {
  const { projectId } = h;
  // Data source CRUD
  register({ name: 'data_source.list', title: '数据源列表', description: '列出项目数据源。', inputSchema: h.schema(['projectId'], { projectId: h.string }), risk: 'read', requiredAccess: 'view', handler: (input, context) => requireProject(projectId(input, context)).srcTable || [] });
  register({ name: 'data_source.get', title: '读取数据源', description: '读取数据源及 Sheet 元数据。', inputSchema: h.schema(['projectId', 'id'], { projectId: h.string, id: h.string }), risk: 'read', requiredAccess: 'view', handler: (input, context) => { const items = requireProject(projectId(input, context)).srcTable || []; const item = items.find((e: any) => e.id === input.id); if (!item) throw toolError('TABLE_NOT_FOUND', `${input.id} 不存在`); return item; } });
  for (const [name, title] of [['data_source.create', '创建数据表'], ['data_source.import', '导入数据源']] as const) register({ name, title, description: '从上传 fileId、业务数据行 rows、CSV 或 config.columns 创建数据源。rows 中每个对象代表一条业务记录，不是字段定义；空表使用 config.columns。config.keyFields 必须位于 config 顶层并匹配 rows 键或 columns.name。', inputSchema: h.schema(['projectId', 'id', 'baseRevision', 'idempotencyKey'], { projectId: h.string, id: h.string, baseRevision: h.string, idempotencyKey: h.string, fileId: h.string, rows: { type: 'array', items: { type: 'object', additionalProperties: true }, description: '业务记录数组；字段名作为列名。不要传 fieldId/title/type 字段定义。' }, csv: h.string, sheetName: h.string, config: dataSourceConfigSchema }), risk: 'write', requiredAccess: 'edit', handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); if ((project.srcTable || []).some((item: any) => item.id === input.id)) throw toolError('TABLE_EXISTS', `数据表 ${input.id} 已存在`); const built = tableFromInput({ ...input, tenantId: context.tenantId }); project.srcTable.push(built.table); project.config.updatedAt = new Date().toISOString(); return h.commitProject(project, built.sourceFiles); } });
  register({ name: 'data_source.update', title: '更新数据源', description: '更新数据源显示元信息；原表和 Sheet 结构只能由专用数据接口修改。', inputSchema: h.schema(['projectId', 'id', 'baseRevision', 'idempotencyKey', 'patch'], { projectId: h.string, id: h.string, baseRevision: h.string, idempotencyKey: h.string, patch: h.object }), risk: 'write', requiredAccess: 'edit', handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const table = (project.srcTable || []).find((item: any) => item.id === input.id); if (!table) throw toolError('TABLE_NOT_FOUND', `${input.id} 不存在`); const protectedFields = ['fileName', 'fileType', 'fileSize', 'dataHash', 'uploadedAt', 'sheets', 'preview', 'rows']; const invalid = protectedFields.find((field) => input.patch?.[field] !== undefined); if (invalid) throw toolError('PROTECTED_DATA_FIELD', `${invalid} 只能由项目数据接口修改`, `patch.${invalid}`); Object.assign(table, input.patch, { id: table.id }); project.config.updatedAt = new Date().toISOString(); return h.commitProject(project); } });
  register({ name: 'data_source.delete', title: '删除数据源', description: '删除数据源；有引用时必须显式 cascade。', inputSchema: h.schema(['projectId', 'id', 'baseRevision', 'idempotencyKey'], { projectId: h.string, id: h.string, baseRevision: h.string, idempotencyKey: h.string, cascade: h.boolean, confirmationToken: h.string }), risk: 'destructive', requiredAccess: 'edit', impact: (input) => ({ dataSourceId: input.id, cascade: !!input.cascade }), handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const refs = (project.forms || []).filter((form: any) => JSON.stringify(form).includes(input.id)); if (refs.length && !input.cascade) throw toolError('RESOURCE_REFERENCED', '数据源仍被表单引用', 'id', { forms: refs.map((item: any) => item.id) }); const idx = (project.srcTable || []).findIndex((item: any) => item.id === input.id); if (idx >= 0) project.srcTable.splice(idx, 1); if (input.cascade) project.forms = (project.forms || []).filter((form: any) => !JSON.stringify(form).includes(input.id)); project.sheetBehaviors = (project.sheetBehaviors || []).filter((item: any) => item.tableId !== input.id); project.config.updatedAt = new Date().toISOString(); return h.commitProject(project); } });

  // Sheet configuration
  register({ name: 'data_sheet.get', title: '读取 Sheet', description: '读取 Sheet 元数据和行版本。', inputSchema: h.schema(['projectId', 'tableId', 'sheetName'], { projectId: h.string, tableId: h.string, sheetName: h.string }), risk: 'read', requiredAccess: 'view', handler: (input, context) => { const table = (requireProject(projectId(input, context)).srcTable || []).find((item: any) => item.id === input.tableId); if (!table) throw toolError('TABLE_NOT_FOUND', '数据表不存在'); const sheet = (table.sheets || []).find((item: any) => item.name === input.sheetName); if (!sheet) throw toolError('SHEET_NOT_FOUND', 'Sheet 不存在'); return sheet; } });
  register({ name: 'data_sheet.configure', title: '配置 Sheet', description: '设置主键、只读、冻结、筛选和排序。', inputSchema: h.schema(['projectId', 'tableId', 'sheetName', 'baseRevision', 'idempotencyKey', 'config'], { projectId: h.string, tableId: h.string, sheetName: h.string, baseRevision: h.string, idempotencyKey: h.string, config: dataSourceConfigSchema }), risk: 'write', requiredAccess: 'edit', handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const table = (project.srcTable || []).find((item: any) => item.id === input.tableId); if (!table) throw toolError('TABLE_NOT_FOUND', '数据表不存在'); const sheet = (table.sheets || []).find((item: any) => item.name === input.sheetName); if (!sheet) throw toolError('SHEET_NOT_FOUND', 'Sheet 不存在'); sheet.config = { ...sheet.config, ...input.config, id: sheet.config?.id || sheet.name, tableName: sheet.name }; project.config.updatedAt = new Date().toISOString(); return h.commitProject(project); } });

  // Key validation
  register({ name: 'data_keys.validate', title: '校验主键', description: '校验指定或已配置的组合主键。', inputSchema: h.schema(['projectId', 'tableId', 'sheetName'], { projectId: h.string, tableId: h.string, sheetName: h.string, keyFields: { type: 'array' } }), risk: 'read', requiredAccess: 'view', handler: (input, context) => { const project = requireProject(projectId(input, context)); const table = (project.srcTable || []).find((item: any) => item.id === input.tableId); if (!table) throw toolError('TABLE_NOT_FOUND', '数据表不存在'); const sheet = (table.sheets || []).find((item: any) => item.name === input.sheetName); if (!sheet) throw toolError('SHEET_NOT_FOUND', 'Sheet 不存在'); const keys = input.keyFields || sheet.config?.keyFields || []; const seen = new Set(); const errors: any[] = []; fullSourceRows(project, table, sheet).forEach((row: any, index: number) => { const values = keys.map((key: string) => row[key]); const hash = JSON.stringify(values); if (values.some((value: any) => value === '' || value == null)) errors.push({ index, code: 'EMPTY_KEY' }); else if (seen.has(hash)) errors.push({ index, code: 'DUPLICATE_KEY', values }); seen.add(hash); }); return { valid: errors.length === 0, keyFields: keys, errors }; } });

  // Row operations
  register({ name: 'data_rows.query', title: '查询数据行', description: '分页搜索、筛选、排序并返回稳定 rowKey。', inputSchema: h.schema(['projectId', 'tableId', 'sheetName'], { projectId: h.string, tableId: h.string, sheetName: h.string, page: { type: 'number', minimum: 1 }, pageSize: { type: 'number', minimum: 1, maximum: 500 }, search: h.string, keySearch: { type: 'object', additionalProperties: true }, sortModel: { type: 'array' }, filterModel: h.object }), risk: 'read', requiredAccess: 'view', handler: (input, context) => queryProjectRows(requireProject(projectId(input, context)), input) });
  register({ name: 'data_rows.batch', title: '批量写回数据', description: '按稳定 rowKey 原子应用新增、更新和删除；单次最多 1000 个变更。', inputSchema: h.schema(['projectId', 'tableId', 'sheetName', 'baseRevision', 'idempotencyKey'], { projectId: h.string, tableId: h.string, sheetName: h.string, baseRevision: h.string, baseVersion: h.string, idempotencyKey: h.string, adds: { type: 'array', items: { type: 'object', additionalProperties: true } }, updates: { type: 'array', items: dataRowUpdateSchema }, deletes: { type: 'array', items: h.string }, confirmationToken: h.string }), risk: 'write', requiredAccess: 'edit', confirmWhen: (input) => Array.isArray(input.deletes) && input.deletes.length > 0, impact: (input) => ({ deletes: input.deletes?.length || 0, tableId: input.tableId, sheetName: input.sheetName }), handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const result = batchProjectRows(project, input); project.config.updatedAt = new Date().toISOString(); const committed = h.commitProject(project, serializeTableSource(project, input.tableId, input.sheetName)); return { ...result, revision: committed.revision }; } });
  register({ name: 'data_rows.transaction', title: '跨表原子写回', description: '在项目副本中预检并应用多个 Sheet 变更，全部成功后一次提交；支持事务内生成键引用。', inputSchema: h.schema(['projectId', 'baseRevision', 'idempotencyKey', 'operations'], { projectId: h.string, baseRevision: h.string, idempotencyKey: h.string, operations: { type: 'array', items: { type: 'object', additionalProperties: true } }, confirmationToken: h.string }), risk: 'write', requiredAccess: 'edit', confirmWhen: (input) => (input.operations || []).some((item: any) => Array.isArray(item.deletes) && item.deletes.length > 0), impact: (input) => ({ tables: (input.operations || []).map((item: any) => `${item.tableId}/${item.sheetName}`), changes: (input.operations || []).reduce((total: number, item: any) => total + (item.adds?.length || 0) + (item.updates?.length || 0) + (item.deletes?.length || 0), 0), deletes: (input.operations || []).reduce((total: number, item: any) => total + (item.deletes?.length || 0), 0) }), handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const result = applyDataRowsTransaction(project, input.operations || []); const sources = (input.operations || []).flatMap((item: any) => serializeTableSource(result.project, item.tableId, item.sheetName)); project.config.updatedAt = new Date().toISOString(); const committed = h.commitProject(result.project, sources); return { applied: result.applied, totalChanges: result.totalChanges, revision: committed.revision }; } });

  // Data relations
  register({ name: 'data_relation.list', title: '数据关系列表', description: '列出项目中声明的等值数据关系。', inputSchema: h.schema(['projectId'], { projectId: h.string }), risk: 'read', requiredAccess: 'view', handler: (input, context) => requireProject(projectId(input, context)).relations || [] });
  register({ name: 'data_relation.suggest', title: '建议数据关系', description: '按字段名称、类型、主键和样本值重合度生成可审计的关系建议，不自动写入。', inputSchema: h.schema(['projectId'], { projectId: h.string }), risk: 'read', requiredAccess: 'view', handler: (input, context) => suggestDataRelations(requireProject(projectId(input, context))) });
  register({ name: 'data_relation.validate', title: '校验数据关系', description: '校验关系两侧表、字段、数量和类型兼容性。', inputSchema: h.schema(['projectId', 'relation'], { projectId: h.string, relation: h.object }), risk: 'read', requiredAccess: 'view', handler: (input, context) => validateRelation(requireProject(projectId(input, context)), input.relation as DataRelation) });
  register({ name: 'data_relation.upsert', title: '保存数据关系', description: '新增或更新正式数据关系；写入前执行完整校验。', inputSchema: h.schema(['projectId', 'baseRevision', 'idempotencyKey', 'relation'], { projectId: h.string, baseRevision: h.string, idempotencyKey: h.string, relation: h.object }), risk: 'write', requiredAccess: 'edit', handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const relation = input.relation as DataRelation; if (!relation?.id) throw toolError('REQUIRED_ARGUMENT', '关系必须包含 id', 'relation.id'); const report = validateRelation(project, relation); if (!report.valid) throw toolError('RELATION_INVALID', '关系定义无效', 'relation', report); project.relations ||= []; const idx = project.relations.findIndex((item: any) => item.id === relation.id); if (idx >= 0) project.relations[idx] = relation; else project.relations.push(relation); project.config.updatedAt = new Date().toISOString(); const committed = h.commitProject(project); return { relation, validation: report, revision: committed.revision }; } });
  register({ name: 'data_relation.delete', title: '删除数据关系', description: '删除关系定义；被模板实例引用时需显式 cascade。', inputSchema: h.schema(['projectId', 'id', 'baseRevision', 'idempotencyKey'], { projectId: h.string, id: h.string, baseRevision: h.string, idempotencyKey: h.string, cascade: h.boolean, confirmationToken: h.string }), risk: 'destructive', requiredAccess: 'edit', impact: (input) => ({ relationId: input.id, cascade: !!input.cascade }), handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const refs = (project.templateInstances || []).filter((item: any) => item.selection?.relationIds?.includes(input.id) || item.parameters?.relationId === input.id); if (refs.length && !input.cascade) throw toolError('RESOURCE_REFERENCED', '关系仍被模板实例引用', 'id', { templateInstances: refs.map((item: any) => item.id) }); project.relations = (project.relations || []).filter((item: any) => item.id !== input.id); if (input.cascade) project.templateInstances = (project.templateInstances || []).filter((item: any) => !refs.includes(item)); project.config.updatedAt = new Date().toISOString(); const committed = h.commitProject(project); return { deleted: true, revision: committed.revision }; } });
  register({ name: 'data_relation.query', title: '关联查询', description: '按已声明关系分页、筛选和排序，保留源主键；exportAll 可返回至多一万条导出数据。', inputSchema: h.schema(['projectId', 'relationId'], { projectId: h.string, relationId: h.string, joinType: { type: 'string', enum: ['inner', 'left'] }, page: { type: 'number' }, pageSize: { type: 'number' }, search: h.string, sortModel: { type: 'array' }, filterModel: h.object, exportAll: h.boolean }), risk: 'read', requiredAccess: 'view', handler: (input, context) => queryRelationRows(requireProject(projectId(input, context)), input as any) });
}
