/**
 * Output, release, and export tools.
 */
import { assertRevision, packageProject, projectRevision, requireProject, toolError, validateProjectModel } from '../project-authoring';
import { inspectProjectQuality } from '../project-quality';
import type { RegisterFn, ToolHelpers } from './types';

function projectId(input: Record<string, any>, context: { projectId?: string }) { return String(input.projectId || context.projectId || ''); }
function findById(items: any[], id: string, code: string) { const item = items.find((entry) => entry.id === id); if (!item) throw toolError(code, `${id} 不存在`); return item; }
function upsert(items: any[], item: any) { const index = items.findIndex((entry) => entry.id === item.id); if (index >= 0) items[index] = item; else items.push(item); return item; }
function remove(items: any[], id: string) { const index = items.findIndex((entry) => entry.id === id); if (index < 0) return false; items.splice(index, 1); return true; }

export function registerDeliveryTools(register: RegisterFn, h: ToolHelpers) {
  // Output CRUD
  register({ name: 'output.list', title: 'output 列表', description: '列出项目 output。', inputSchema: h.schema(['projectId'], { projectId: h.string }), risk: 'read', requiredAccess: 'view', handler: (input, context) => requireProject(projectId(input, context)).outputs || [] });
  register({ name: 'output.get', title: '读取 output', description: '读取指定 output。', inputSchema: h.schema(['projectId', 'id'], { projectId: h.string, id: h.string }), risk: 'read', requiredAccess: 'view', handler: (input, context) => findById(requireProject(projectId(input, context)).outputs || [], input.id, 'OUTPUT_NOT_FOUND') });
  register({ name: 'output.create', title: '创建 output', description: '按稳定 ID 创建输出定义。', inputSchema: h.schema(['projectId', 'item', 'baseRevision', 'idempotencyKey'], { projectId: h.string, id: h.string, item: h.object, baseRevision: h.string, idempotencyKey: h.string }), risk: 'write', requiredAccess: 'edit', handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); project.outputs ||= []; const item = input.item; if (!item.id) throw toolError('INVALID_ID', 'item.id 不能为空', 'item.id'); if (project.outputs.some((entry: any) => entry.id === item.id)) throw toolError('RESOURCE_EXISTS', 'output 已存在'); upsert(project.outputs, item); project.config.updatedAt = new Date().toISOString(); return h.commitProject(project); } });
  register({ name: 'output.update', title: '更新 output', description: '按稳定 ID 替换输出定义。', inputSchema: h.schema(['projectId', 'item', 'baseRevision', 'idempotencyKey'], { projectId: h.string, id: h.string, item: h.object, baseRevision: h.string, idempotencyKey: h.string }), risk: 'write', requiredAccess: 'edit', handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); project.outputs ||= []; const item = input.item; if (!item.id) throw toolError('INVALID_ID', 'item.id 不能为空', 'item.id'); upsert(project.outputs, item); project.config.updatedAt = new Date().toISOString(); return h.commitProject(project); } });
  register({ name: 'output.delete', title: '删除 output', description: '删除指定 output。', inputSchema: h.schema(['projectId', 'id', 'baseRevision', 'idempotencyKey'], { projectId: h.string, id: h.string, baseRevision: h.string, idempotencyKey: h.string, confirmationToken: h.string, cascade: h.boolean }), risk: 'destructive', requiredAccess: 'edit', impact: (input) => ({ type: 'output', id: input.id }), handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); remove(project.outputs || [], input.id); project.config.updatedAt = new Date().toISOString(); return h.commitProject(project); } });
  register({ name: 'output.upsert', title: '保存输出定义', description: '按稳定 ID 新增或替换输出定义。', inputSchema: h.schema(['projectId', 'item', 'baseRevision', 'idempotencyKey'], { projectId: h.string, item: h.object, baseRevision: h.string, idempotencyKey: h.string }), risk: 'write', requiredAccess: 'edit', handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); upsert(project.outputs ||= [], input.item); project.config.updatedAt = new Date().toISOString(); return h.commitProject(project); } });

  // Output generation
  register({ name: 'output.generate', title: '生成输出', description: '按输出定义导出项目数据或项目包。', inputSchema: h.schema(['projectId', 'id'], { projectId: h.string, id: h.string }), risk: 'read', requiredAccess: 'run', handler: async (input, context) => { const project = requireProject(projectId(input, context)); const output = findById(project.outputs || [], input.id, 'OUTPUT_NOT_FOUND'); if (output.format === 'json') return { format: 'json', content: { id: project.config.id, name: project.config.name } }; const buffer = await packageProject(project.config.id); return { format: 'formflow', fileName: `${project.config.id}.formflow`, encoding: 'base64', content: buffer.toString('base64'), bytes: buffer.length }; } });

  // Release management
  register({ name: 'release.get', title: '读取发布状态', description: '读取项目 release 配置。', inputSchema: h.schema(['projectId'], { projectId: h.string }), risk: 'read', requiredAccess: 'view', handler: (input, context) => requireProject(projectId(input, context)).release });
  register({ name: 'release.update', title: '更新发布草稿', description: '更新默认表单、默认 Sheet 和设计入口权限等发布草稿，不切换发布模式。', inputSchema: h.schema(['projectId', 'patch', 'baseRevision', 'idempotencyKey'], { projectId: h.string, patch: h.object, baseRevision: h.string, idempotencyKey: h.string }), risk: 'write', requiredAccess: 'edit', handler: (input, context) => { if (input.patch?.mode !== undefined || input.patch?.lastVerifiedAt !== undefined) throw toolError('INVALID_ARGUMENT', 'mode 和 lastVerifiedAt 只能由 release.apply 更新', 'patch'); const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); project.release = { ...project.release, ...(input.patch || {}) }; project.config.updatedAt = new Date().toISOString(); return h.commitProject(project); } });
  register({ name: 'release.preview', title: '发布预检', description: '执行结构、绑定、主键和最近回归门禁但不修改项目。', inputSchema: h.schema(['projectId'], { projectId: h.string }), risk: 'read', requiredAccess: 'edit', handler: (input, context) => { const project = requireProject(projectId(input, context)); const quality = inspectProjectQuality(project); return { ready: quality.ready, release: project.release, validation: quality.validation, quality, revision: projectRevision(project) }; } });
  register({ name: 'release.apply', title: '应用发布', description: '通过校验后切换 design/test/use 状态；use 会关闭设计器、行为编辑器和流程编辑器入口，design/test 保持这些入口可用。', inputSchema: h.schema(['projectId', 'mode', 'baseRevision', 'idempotencyKey'], { projectId: h.string, mode: { type: 'string', enum: ['design', 'test', 'use'] }, baseRevision: h.string, idempotencyKey: h.string, confirmationToken: h.string }), risk: 'destructive', requiredAccess: 'manage', impact: (input) => ({ projectId: input.projectId, releaseMode: input.mode, editorAccess: input.mode === 'use' ? 'disabled' : 'enabled' }), handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const report = validateProjectModel(project); if (!report.valid) throw toolError('RELEASE_VALIDATION_FAILED', '项目未通过发布校验', undefined, report); if (!['design', 'test', 'use'].includes(input.mode)) throw toolError('INVALID_RELEASE_MODE', 'mode 必须为 design、test 或 use'); project.release = { ...project.release, mode: input.mode, lastVerifiedAt: new Date().toISOString(), allowDesigner: input.mode !== 'use', allowBehaviorEditor: input.mode !== 'use', allowWorkflowEditor: input.mode !== 'use' }; project.config.updatedAt = new Date().toISOString(); return h.commitProject(project); } });
}
