/**
 * Form, component, binding, and preview tools.
 */
import { assertRevision, generatedForm, normalizeFormComponents, normalizeFormDesign, requireProject, toolError } from '../project-authoring';
import { applyBehaviorDslToComponents, hasBehaviorDslErrors } from '../../../../shared/formflow-core/behaviorDsl';
import { getFormTemplate } from '../../../../shared/form-templates';
import { formContext } from '../rule-agent';
import { formComponentItemSchema } from '../tool-shared';
import type { RegisterFn, ToolHelpers } from './types';

export function registerFormTools(register: RegisterFn, h: ToolHelpers) {
  const { projectId, findById, upsert, remove } = h;
  const resolveTemplate = (templateId?: string) => {
    if (!templateId) return undefined;
    const template = getFormTemplate(String(templateId));
    if (!template) throw toolError('FORM_TEMPLATE_NOT_FOUND', `表单模板 ${templateId} 不存在`, 'templateId');
    return template;
  };
  register({ name: 'form.list', title: '表单列表', description: '列出项目表单。', inputSchema: h.schema(['projectId'], { projectId: h.string }), risk: 'read', requiredAccess: 'view', examples: [{ summary: '列出项目表单', arguments: { projectId: 'device_mgmt' } }], handler: (input, context) => (requireProject(projectId(input, context)).forms || []).map((form: any) => ({ id: form.id, name: form.name, mode: form.design?.formMode, updatedAt: form.updatedAt })) });
  register({ name: 'form.get', title: '读取表单', description: '读取表单设计、行为和规则。', inputSchema: h.schema(['projectId', 'id'], { projectId: h.string, id: h.string }), risk: 'read', requiredAccess: 'view', examples: [{ summary: '读取 device_edit 表单', arguments: { projectId: 'device_mgmt', id: 'device_edit' } }], handler: (input, context) => findById(requireProject(projectId(input, context)).forms || [], input.id, 'FORM_NOT_FOUND') });
  register({ name: 'form.create', title: '创建表单', description: '创建空表单、按模板初始化或保存完整设计；服务端会补齐表单窗体与控件几何。', inputSchema: h.schema(['projectId', 'id', 'name', 'baseRevision', 'idempotencyKey'], { projectId: h.string, id: h.string, name: h.string, mode: { type: 'string', enum: ['create', 'edit', 'detail', 'lookup-edit'] }, templateId: h.string, baseRevision: h.string, idempotencyKey: h.string, design: h.object }), risk: 'write', requiredAccess: 'edit', examples: [{ summary: '按空白模板创建表单', arguments: { projectId: 'device_mgmt', id: 'device_create', name: '设备录入', mode: 'create', templateId: 'blank', baseRevision: '<revision>', idempotencyKey: 'form-1' }, success: { revision: '…' }, errors: [{ code: 'FORM_EXISTS', message: '表单已存在' }, { code: 'FORM_TEMPLATE_NOT_FOUND', message: '模板不存在' }] }], handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const template = resolveTemplate(input.templateId); if ((project.forms || []).some((item: any) => item.id === input.id)) throw toolError('FORM_EXISTS', '表单已存在'); const now = new Date().toISOString(); const base = input.design || { id: `${input.id}_design`, name: input.name, formMode: input.mode || template?.formMode || 'create', viewport: { zoom: 1, panX: 0, panY: 0 }, gridSize: 12, formWindow: { x: 40, y: 40, width: 900, height: 600, props: { title: input.name, showFooter: false } }, components: [], bindings: [], templateKey: input.templateId, templateParameters: template ? { formTemplate: { key: template.key, label: template.label, formMode: template.formMode, scaffoldFromTable: template.scaffoldFromTable, requiresRelation: template.requiresRelation } } : undefined }; const supplied = { ...base, ...(input.templateId && !(base as any).templateKey ? { templateKey: String(input.templateId) } : {}), ...(template && !(base as any).formMode ? { formMode: template.formMode } : {}) }; const design = { ...normalizeFormDesign(supplied), createdAt: supplied.createdAt || now, updatedAt: supplied.updatedAt || now }; project.forms.push({ id: input.id, name: input.name, design, behaviors: [], ruleCode: '', createdAt: design.createdAt, updatedAt: design.updatedAt }); project.release.defaultFormId ||= input.id; project.config.updatedAt = now; return h.commitProject(project); } });
  register({ name: 'form.generate_from_table', title: '从数据表生成表单', description: '按模板（可选）与列类型、主键生成 create/edit/detail/lookup-edit 表单；未传 templateId/mode 时默认 edit。', inputSchema: h.schema(['projectId', 'tableId', 'sheetName', 'id', 'baseRevision', 'idempotencyKey'], { projectId: h.string, tableId: h.string, sheetName: h.string, id: h.string, mode: { type: 'string', enum: ['create', 'edit', 'detail', 'lookup-edit'] }, templateId: h.string, baseRevision: h.string, idempotencyKey: h.string }), risk: 'write', requiredAccess: 'edit', examples: [{ summary: '用查询修改模板生成编辑表单（id 必须是新表单 id）', arguments: { projectId: 'device_mgmt', tableId: 'device', sheetName: 'Sheet1', id: 'device_edit', templateId: 'lookup-edit', baseRevision: '<revision>', idempotencyKey: 'form-2' }, success: { revision: '…' }, errors: [{ code: 'FORM_EXISTS', message: '表单已存在（id 冲突，换新 id 或改用 form.update）' }, { code: 'TABLE_NOT_FOUND', message: 'tableId 不存在' }] }], handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const template = resolveTemplate(input.templateId); const table = findById(project.srcTable || [], input.tableId, 'TABLE_NOT_FOUND'); const sheet = (table.sheets || []).find((item: any) => item.name === input.sheetName); if (!sheet) throw toolError('SHEET_NOT_FOUND', 'Sheet 不存在'); const mode = input.mode || template?.formMode || 'edit'; const form = generatedForm(table, sheet, { ...input, mode, templateKey: input.templateId }); if ((project.forms || []).some((item: any) => item.id === form.id)) throw toolError('FORM_EXISTS', '表单已存在'); project.forms.push(form); project.release.defaultFormId ||= form.id; project.config.updatedAt = new Date().toISOString(); return h.commitProject(project); } });
  register({ name: 'form.update', title: '更新表单', description: '更新表单元信息和设计；设计控件会规范化布局，行为与规则由 behavior MCP 管理。', inputSchema: h.schema(['projectId', 'id', 'baseRevision', 'idempotencyKey', 'patch'], { projectId: h.string, id: h.string, baseRevision: h.string, idempotencyKey: h.string, patch: h.object }), risk: 'write', requiredAccess: 'edit', examples: [{ summary: '更新表单名称', arguments: { projectId: 'device_mgmt', id: 'device_edit', baseRevision: '<revision>', idempotencyKey: 'upd-1', patch: { name: '设备查询编辑' } } }], handler: (input, context) => { if (input.patch?.ruleCode !== undefined || input.patch?.behaviors !== undefined) throw toolError('INVALID_ARGUMENT', 'ruleCode 和 behaviors 必须由 behavior MCP 更新', 'patch'); const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const form = findById(project.forms || [], input.id, 'FORM_NOT_FOUND'); const now = new Date().toISOString(); const patch = { ...input.patch }; if (patch.design) patch.design = { ...normalizeFormDesign(patch.design), createdAt: patch.design.createdAt || form.design?.createdAt || form.createdAt || now, updatedAt: now }; Object.assign(form, patch, { id: form.id, updatedAt: now }); project.config.updatedAt = now; return h.commitProject(project); } });
  register({ name: 'form.delete', title: '删除表单', description: '删除表单并检查 release 默认引用。', inputSchema: h.schema(['projectId', 'id', 'baseRevision', 'idempotencyKey'], { projectId: h.string, id: h.string, baseRevision: h.string, idempotencyKey: h.string, confirmationToken: h.string, cascade: h.boolean }), risk: 'destructive', requiredAccess: 'edit', impact: (input) => ({ formId: input.id }), examples: [{ summary: '删除表单（需确认）', arguments: { projectId: 'device_mgmt', id: 'device_create', baseRevision: '<revision>', idempotencyKey: 'del-1' } }], handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); if (project.release?.defaultFormId === input.id && !input.cascade) throw toolError('RESOURCE_REFERENCED', '表单是 release 默认表单；需 cascade=true'); remove(project.forms, input.id); if (project.release?.defaultFormId === input.id) project.release.defaultFormId = project.forms[0]?.id; project.config.updatedAt = new Date().toISOString(); return h.commitProject(project); } });

  // Component and binding CRUD
  for (const kind of ['component', 'binding'] as const) {
    register({ name: `form_${kind}.upsert`, title: `保存表单${kind === 'component' ? '控件' : '绑定'}`, description: kind === 'component' ? '按稳定 ID 新增或局部更新控件；表单窗体是实例固有配置，不能作为 form 控件新增。按钮动作使用 props.events 的非空脚本，或 props.flowTriggers 中指向现有流程的启用触发器。' : '按稳定 ID 新增或替换表单绑定。', inputSchema: h.schema(['projectId', 'formId', 'item', 'baseRevision', 'idempotencyKey'], { projectId: h.string, formId: h.string, item: kind === 'component' ? formComponentItemSchema : h.object, baseRevision: h.string, idempotencyKey: h.string }), risk: 'write', requiredAccess: 'edit', examples: kind === 'component'
      ? [{ summary: '新增一个数字输入控件并绑定字段', arguments: { projectId: 'device_mgmt', formId: 'device_edit', baseRevision: '<revision>', idempotencyKey: 'cmp-1', item: { id: 'field_score', type: 'number', fieldBinding: '评分', props: { name: '评分', label: '评分' } } } }]
      : [{ summary: '把表单绑定到 device 表', arguments: { projectId: 'device_mgmt', formId: 'device_edit', baseRevision: '<revision>', idempotencyKey: 'bnd-1', item: { id: 'device_binding', sourceId: 'device', targetId: 'device_edit', type: 'table', config: { tableId: 'device', sheetName: 'Sheet1' } } } }], handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const form = findById(project.forms || [], input.formId, 'FORM_NOT_FOUND'); const collection = kind === 'component' ? (form.design.components ||= []) : (form.design.bindings ||= []); if (!input.item.id) throw toolError('INVALID_ID', 'item.id 不能为空', 'item.id'); if (kind === 'component') { if (input.item.type === 'form') throw toolError('FORM_WINDOW_IS_INTRINSIC', '表单窗体属于表单实例，不能作为控件新增', 'item.type'); const existing = collection.find((item: any) => item.id === input.item.id); const merged = existing ? { ...existing, ...input.item, props: { ...(existing.props || {}), ...(input.item.props || {}) } } : input.item; upsert(collection, normalizeFormComponents([merged])[0]); } else upsert(collection, input.item); form.updatedAt = new Date().toISOString(); project.config.updatedAt = new Date().toISOString(); return h.commitProject(project); } });
    register({ name: `form_${kind}.delete`, title: `删除表单${kind === 'component' ? '控件' : '绑定'}`, description: `删除指定表单${kind === 'component' ? '控件' : '绑定'}。`, inputSchema: h.schema(['projectId', 'formId', 'id', 'baseRevision', 'idempotencyKey'], { projectId: h.string, formId: h.string, id: h.string, baseRevision: h.string, idempotencyKey: h.string, confirmationToken: h.string }), risk: 'destructive', requiredAccess: 'edit', impact: (input) => ({ formId: input.formId, [kind + 'Id']: input.id }), examples: [{ summary: `删除表单${kind === 'component' ? '控件' : '绑定'}（需确认）`, arguments: { projectId: 'device_mgmt', formId: 'device_edit', id: 'field_score', baseRevision: '<revision>', idempotencyKey: 'del-1' } }], handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const form = findById(project.forms || [], input.formId, 'FORM_NOT_FOUND'); const collection = kind === 'component' ? form.design.components : form.design.bindings; remove(collection || [], input.id); if (kind === 'component') { for (const component of form.design.components || []) { component.children = (component.children || []).filter((id: string) => id !== input.id); if (component.parentId === input.id) delete component.parentId; } form.design.bindings = (form.design.bindings || []).filter((binding: any) => binding.sourceId !== input.id && binding.targetId !== input.id); } project.config.updatedAt = new Date().toISOString(); return h.commitProject(project); } });
  }

  // Form preview and state
  register({ name: 'form.preview', title: '表单预览', description: '返回可供模型检查的表单字段、控件和绑定摘要。', inputSchema: h.schema(['projectId', 'formId'], { projectId: h.string, formId: h.string }), risk: 'read', requiredAccess: 'view', examples: [{ summary: '预览 device_edit 的字段与控件', arguments: { projectId: 'device_mgmt', formId: 'device_edit' } }], handler: (input) => { const context = formContext(input.projectId, input.formId); return { form: context.form, fields: context.fields, components: context.components.map((item: any) => ({ id: item.id, type: item.type, field: item.fieldBinding, label: item.props?.label })) }; } });
  register({ name: 'form_state.read', title: '读取表单状态', description: '读取表单结构和脱敏运行时值。', inputSchema: h.schema(['formId'], { projectId: h.string, formId: h.string, runtime: h.object }), risk: 'read', requiredAccess: 'view', examples: [{ summary: '读取表单运行时状态', arguments: { projectId: 'device_mgmt', formId: 'device_edit' } }], handler: (input, context) => { const pid = projectId(input, context); const { form, components, fields } = formContext(pid, input.formId); const sensitive = /(password|passwd|pwd|token|secret|api.?key|身份证|手机|电话|phone|mobile|email|邮箱)/i; const runtime = input.runtime || { source: 'synthetic', values: {} }; const values = Object.fromEntries(Object.entries(runtime.values || {}).map(([field, value]) => sensitive.test(field) ? [field, { masked: true, present: value != null && String(value).length > 0 }] : [field, value])); return { formId: input.formId, formName: form.name, fields, components: components.map((item: any) => ({ id: item.id, type: item.type, field: item.fieldBinding || item.props?.name, label: item.props?.label })), runtime: { ...runtime, values } }; } });
}
