/**
 * Quality, mock data, testing, and analysis tools.
 */
import { assertRevision, batchProjectRows, projectRevision, requireProject, serializeTableSource, toolError } from '../project-authoring';
import { generateMockData, generateProjectTestSuite, profileMockData, runProjectTests } from '../project-quality';
import { analysisRunStatus, appendAnalysisRun, applyPredictionWriteback, runAnalysisTemplate } from '../analysis-template-runtime';
import type { RegisterFn, ToolHelpers } from './types';

/** 注册质量域工具（质量检查/测试生成运行）。 */
export function registerQualityTools(register: RegisterFn, h: ToolHelpers) {
  const { projectId, upsert } = h;
  // Mock data
  register({ name: 'mock_data.profile', title: '分析 Mock 数据模型', description: '分析列类型、主键和本地化生成器，不修改项目。', inputSchema: h.schema(['projectId', 'tableId', 'sheetName'], { projectId: h.string, tableId: h.string, sheetName: h.string }), risk: 'read', requiredAccess: 'view', examples: [{ summary: '分析 device 表 Mock 模型', arguments: { projectId: 'device_mgmt', tableId: 'device', sheetName: 'Sheet1' } }], handler: (input, context) => profileMockData(requireProject(projectId(input, context)), input as any) });
  for (const name of ['generate', 'preview'] as const) register({ name: `mock_data.${name}`, title: `${name === 'generate' ? '生成' : '预览'} Mock 数据`, description: '按固定 seed 生成可追加的有效行和隔离负向场景。', inputSchema: h.schema(['projectId', 'tableId', 'sheetName'], { projectId: h.string, tableId: h.string, sheetName: h.string, rowCount: { type: 'number' }, seed: {}, scenarios: { type: 'array' } }), risk: 'read', requiredAccess: 'view', examples: [{ summary: `${name === 'generate' ? '生成' : '预览'} 5 行 Mock 数据`, arguments: { projectId: 'device_mgmt', tableId: 'device', sheetName: 'Sheet1', rowCount: 5, seed: 42 } }], handler: (input, context) => generateMockData(requireProject(projectId(input, context)), input as any) });
  register({ name: 'mock_data.apply', title: '追加 Mock 数据', description: '确定性生成并向目标 Sheet 追加有效 Mock 行；负向场景只保存为隔离夹具。', inputSchema: h.schema(['projectId', 'tableId', 'sheetName', 'baseRevision', 'idempotencyKey'], { projectId: h.string, tableId: h.string, sheetName: h.string, rowCount: { type: 'number' }, seed: {}, scenarios: { type: 'array' }, baseRevision: h.string, idempotencyKey: h.string }), risk: 'write', requiredAccess: 'edit', handler: (input, context) => {
    const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const generated = generateMockData(project, input as any); const result = batchProjectRows(project, { tableId: input.tableId, sheetName: input.sheetName, adds: generated.rows });
    project.testing ||= { profiles: [], suites: [], fixtures: [], runs: [] };
    upsert(project.testing.profiles ||= [], { id: generated.id, ...profileMockData(project, input as any), seed: generated.seed, updatedAt: new Date().toISOString() });
    upsert(project.testing.fixtures ||= [], { id: generated.id, seed: generated.seed, tableId: input.tableId, sheetName: input.sheetName, scenarios: generated.isolatedCases, updatedAt: new Date().toISOString() });
    project.config.updatedAt = new Date().toISOString();
    const committed = h.commitProject(project, serializeTableSource(project, input.tableId, input.sheetName));
    return { ...result, generated: generated.rows.length, isolatedCases: generated.isolatedCases.length, seed: generated.seed, revision: committed.revision };
  } });

  // Project testing
  register({ name: 'project_test.generate', title: '生成项目回归套件', description: '根据表单约束生成并持久化主路径和失败路径用例。', inputSchema: h.schema(['projectId', 'baseRevision', 'idempotencyKey'], { projectId: h.string, seed: {}, baseRevision: h.string, idempotencyKey: h.string }), risk: 'write', requiredAccess: 'edit', examples: [{ summary: '生成回归测试套件', arguments: { projectId: 'device_mgmt', baseRevision: '<revision>', idempotencyKey: 'test-gen-1' } }], handler: (input, context) => {
    const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const suite = generateProjectTestSuite(project, Number(input.seed || 20260715)); project.testing ||= { profiles: [], suites: [], fixtures: [], runs: [] }; upsert(project.testing.suites ||= [], suite); project.config.updatedAt = new Date().toISOString(); h.commitProject(project); return suite;
  } });
  register({ name: 'project_test.run', title: '运行项目回归', description: '运行结构、规则沙箱和表单约束测试并持久化有界结果。', inputSchema: h.schema(['projectId', 'baseRevision', 'idempotencyKey'], { projectId: h.string, suiteId: h.string, baseRevision: h.string, idempotencyKey: h.string }), risk: 'write', requiredAccess: 'edit', examples: [{ summary: '运行项目回归测试', arguments: { projectId: 'device_mgmt', baseRevision: '<revision>', idempotencyKey: 'test-run-1' } }], handler: (input, context) => {
    const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const suite = input.suiteId ? (project.testing?.suites || []).find((item: any) => item.id === input.suiteId) : undefined; if (input.suiteId && !suite) throw toolError('TEST_SUITE_NOT_FOUND', '测试套件不存在'); const run = runProjectTests(project, suite); project.testing ||= { profiles: [], suites: [], fixtures: [], runs: [] }; project.testing.runs = [...(project.testing.runs || []), run].slice(-20); project.config.updatedAt = new Date().toISOString(); h.commitProject(project); return run;
  } });
  register({ name: 'project_test.history', title: '读取回归历史', description: '读取持久化测试套件和最近二十次运行摘要。', inputSchema: h.schema(['projectId'], { projectId: h.string }), risk: 'read', requiredAccess: 'view', examples: [{ summary: '查看回归历史', arguments: { projectId: 'device_mgmt' } }], handler: (input, context) => { const testing = requireProject(projectId(input, context)).testing || {}; return { suites: testing.suites || [], fixtures: testing.fixtures || [], runs: testing.runs || [] }; } });

  // Analysis
  register({ name: 'project_analysis.run', title: '运行分析或预测模板', description: '对当前数据版本运行分析/预测，记录配置、指标、基线、模型版本、完整结果和质量结论；低于基线的预测不会标记为可用。', inputSchema: h.schema(['projectId', 'templateId', 'tableId', 'sheetName', 'baseRevision', 'idempotencyKey'], { projectId: h.string, templateId: h.string, tableId: h.string, tableIds: { type: 'array' }, relationIds: { type: 'array' }, sheetName: h.string, fields: { type: 'array' }, parameters: h.object, baseRevision: h.string, idempotencyKey: h.string }), risk: 'write', ownerRole: 'quality', requiredAccess: 'edit', handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const revision = projectRevision(project); const run = runAnalysisTemplate(project, input as any, revision); project.config.updatedAt = new Date().toISOString(); const committed = h.commitProject(appendAnalysisRun(project, run.record)); return { ...run, revision: committed.revision }; } });
  register({ name: 'project_analysis.list', title: '分析与预测结果', description: '列出结果并按当前输入数据版本标记是否过期。', inputSchema: h.schema(['projectId'], { projectId: h.string }), risk: 'read', ownerRole: 'quality', requiredAccess: 'view', handler: (input, context) => { const project = requireProject(projectId(input, context)); return (project.modelRuns || []).map((record: any) => analysisRunStatus(project, record)); } });
  register({ name: 'project_analysis.status', title: '分析结果状态', description: '检查单个结果是否因输入数据变化而过期，并返回可操作原因。', inputSchema: h.schema(['projectId', 'id'], { projectId: h.string, id: h.string }), risk: 'read', ownerRole: 'quality', requiredAccess: 'view', handler: (input, context) => { const project = requireProject(projectId(input, context)); const record = (project.modelRuns || []).find((item: any) => item.id === input.id); if (!record) throw toolError('ANALYSIS_RUN_NOT_FOUND', '分析结果不存在', 'id'); return analysisRunStatus(project, record); } });
  register({ name: 'project_analysis.writeback', title: '写回预测结果', description: '把可用回归或分类结果按原始稳定行键写回新字段；输入数据变化时拒绝，覆盖已有字段需确认。', inputSchema: h.schema(['projectId', 'id', 'fieldName', 'baseRevision', 'idempotencyKey'], { projectId: h.string, id: h.string, fieldName: h.string, overwrite: h.boolean, baseRevision: h.string, idempotencyKey: h.string, confirmationToken: h.string }), risk: 'write', ownerRole: 'quality', requiredAccess: 'edit', confirmWhen: (input) => !!input.overwrite, impact: (input) => ({ runId: input.id, fieldName: input.fieldName, overwrite: !!input.overwrite }), handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const result = applyPredictionWriteback(project, input.id, String(input.fieldName), !!input.overwrite); result.project.config.updatedAt = new Date().toISOString(); const committed = h.commitProject(result.project, serializeTableSource(result.project, result.tableId, result.sheetName)); return { applied: result.applied, fieldName: result.fieldName, dataVersion: result.dataVersion, revision: committed.revision }; } });
  register({ name: 'project_analysis.history', title: '读取分析与模型运行历史', description: '读取最近五十次分析/预测运行的有界摘要，不复制业务数据。', inputSchema: h.schema(['projectId'], { projectId: h.string }), risk: 'read', ownerRole: 'quality', requiredAccess: 'view', handler: (input, context) => ({ runs: requireProject(projectId(input, context)).modelRuns || [] }) });
}
