/**
 * Workflow, node, and edge tools.
 */
import { assertRevision, requireProject, toolError, validateProjectModel } from '../project-authoring';
import { normalizeWorkflowNode, normalizeWorkflowEdge, normalizeWorkflowItem, workflowEdgeSchema, workflowItemSchema, workflowNodeSchema } from '../tool-shared';
import type { RegisterFn, ToolHelpers } from './types';

export function registerWorkflowTools(register: RegisterFn, h: ToolHelpers) {
  const { projectId, findById, upsert, remove } = h;
  // Workflow CRUD
  register({ name: 'workflow.list', title: 'workflow 列表', description: '列出项目 workflow。', inputSchema: h.schema(['projectId'], { projectId: h.string }), risk: 'read', requiredAccess: 'view', handler: (input, context) => requireProject(projectId(input, context)).workflows || [] });
  register({ name: 'workflow.get', title: '读取 workflow', description: '读取指定 workflow。', inputSchema: h.schema(['projectId', 'id'], { projectId: h.string, id: h.string }), risk: 'read', requiredAccess: 'view', handler: (input, context) => findById(requireProject(projectId(input, context)).workflows || [], input.id, 'WORKFLOW_NOT_FOUND') });
  for (const action of ['create', 'update'] as const) register({ name: `workflow.${action}`, title: `${action === 'create' ? '创建' : '更新'} workflow`, description: `按稳定 ID ${action === 'create' ? '创建' : '替换'}工作流；节点使用 specId/position/data，连线使用 source/target 节点 ID 和 out:/in: 端口。`, inputSchema: h.schema(['projectId', 'item', 'baseRevision', 'idempotencyKey'], { projectId: h.string, id: h.string, item: workflowItemSchema, baseRevision: h.string, idempotencyKey: h.string }), risk: 'write', requiredAccess: 'edit', handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); project.workflows ||= []; const item = normalizeWorkflowItem(input.item, input.id); if (!item.id) throw toolError('INVALID_ID', 'item.id 不能为空', 'item.id'); if (action === 'create' && project.workflows.some((entry: any) => entry.id === item.id)) throw toolError('RESOURCE_EXISTS', 'workflow 已存在'); upsert(project.workflows, item); project.config.updatedAt = new Date().toISOString(); return h.commitProject(project); } });
  register({ name: 'workflow.delete', title: '删除 workflow', description: '删除指定 workflow。', inputSchema: h.schema(['projectId', 'id', 'baseRevision', 'idempotencyKey'], { projectId: h.string, id: h.string, baseRevision: h.string, idempotencyKey: h.string, confirmationToken: h.string, cascade: h.boolean }), risk: 'destructive', requiredAccess: 'edit', impact: (input) => ({ type: 'workflow', id: input.id }), handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const refs = (project.forms || []).filter((form: any) => JSON.stringify(form).includes(input.id)); if (refs.length && !input.cascade) throw toolError('RESOURCE_REFERENCED', '流程仍被表单引用', 'id', { forms: refs.map((item: any) => item.id) }); remove(project.workflows || [], input.id); project.config.updatedAt = new Date().toISOString(); return h.commitProject(project); } });

  // Node and edge CRUD
  for (const kind of ['node', 'edge'] as const) for (const action of ['upsert', 'delete'] as const) register({ name: `workflow_${kind}.${action}`, title: `${action === 'upsert' ? '保存' : '删除'}流程${kind === 'node' ? '节点' : '连线'}`, description: `按稳定 ID ${action} 工作流${kind}。`, inputSchema: h.schema(['projectId', 'workflowId', action === 'upsert' ? 'item' : 'id', 'baseRevision', 'idempotencyKey'], { projectId: h.string, workflowId: h.string, item: kind === 'node' ? workflowNodeSchema : workflowEdgeSchema, id: h.string, baseRevision: h.string, idempotencyKey: h.string, confirmationToken: h.string, cascade: h.boolean }), risk: action === 'delete' ? 'destructive' : 'write', requiredAccess: 'edit', impact: (input) => ({ workflowId: input.workflowId, kind, id: input.id, cascade: !!input.cascade }), handler: (input, context) => { const project = requireProject(projectId(input, context)); assertRevision(project, input.baseRevision); const flow = findById(project.workflows || [], input.workflowId, 'WORKFLOW_NOT_FOUND'); const collection = kind === 'node' ? (flow.nodes ||= []) : (flow.edges ||= []); if (action === 'upsert') upsert(collection, kind === 'node' ? normalizeWorkflowNode(input.item) : normalizeWorkflowEdge(input.item)); else { const referenced = kind === 'node' && (flow.edges || []).some((edge: any) => edge.source === input.id || edge.target === input.id); if (referenced && !input.cascade) throw toolError('RESOURCE_REFERENCED', '节点仍被连线引用；需 cascade=true'); if (referenced) flow.edges = (flow.edges || []).filter((edge: any) => edge.source !== input.id && edge.target !== input.id); remove(collection, input.id); } project.config.updatedAt = new Date().toISOString(); return h.commitProject(project); } });

  // Workflow validation
  register({ name: 'workflow.validate', title: '校验工作流', description: '校验单个工作流节点、边和端口引用。', inputSchema: h.schema(['projectId', 'id'], { projectId: h.string, id: h.string }), risk: 'read', requiredAccess: 'view', handler: (input, context) => { const project = requireProject(projectId(input, context)); findById(project.workflows || [], input.id, 'WORKFLOW_NOT_FOUND'); const report = validateProjectModel(project); return { valid: !report.errors.some((item) => item.path.startsWith(`workflows.${input.id}`)), errors: report.errors.filter((item) => item.path.startsWith(`workflows.${input.id}`)) }; } });
}
