import type React from 'react';

export const ios = {
  field: {
    width: '100%',
    height: '100%',
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 6,
    padding: '4px',
    boxSizing: 'border-box',
    overflow: 'hidden',
  } satisfies React.CSSProperties,
  label: {
    flex: '0 0 auto',
    minWidth: 0,
    fontSize: 13,
    lineHeight: 1.25,
    fontWeight: 600,
    color: '#1c1c1e',
    letterSpacing: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  } satisfies React.CSSProperties,
  control: {
    flex: '0 0 auto',
    minWidth: 0,
    minHeight: 36,
    width: '100%',
    maxWidth: '100%',
    height: 40,
    padding: '0 12px',
    border: '0.5px solid rgba(60,60,67,0.08)',
    borderRadius: 10,
    background: 'rgba(118,118,128,0.10)',
    color: '#1c1c1e',
    fontSize: 14,
    lineHeight: 1.25,
    outline: 'none',
    boxSizing: 'border-box',
    boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.45)',
    backdropFilter: 'blur(20px) saturate(180%)',
  } satisfies React.CSSProperties,
  fillControl: {
    flex: '1 1 auto',
    minWidth: 0,
    minHeight: 0,
    width: '100%',
    height: '100%',
    padding: '9px 12px',
    border: '0.5px solid rgba(60,60,67,0.08)',
    borderRadius: 10,
    background: 'rgba(118,118,128,0.10)',
    color: '#1c1c1e',
    fontSize: 14,
    lineHeight: 1.35,
    outline: 'none',
    boxSizing: 'border-box',
    boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.45)',
    backdropFilter: 'blur(20px) saturate(180%)',
  } satisfies React.CSSProperties,
  glass: {
    flex: '1 1 0',
    minWidth: 0,
    minHeight: 0,
    width: '100%',
    height: '100%',
    boxSizing: 'border-box',
    background: 'rgba(255,255,255,0.72)',
    border: '0.5px solid rgba(60,60,67,0.10)',
    borderRadius: 10,
    overflow: 'hidden',
    boxShadow: '0 1px 2px rgba(0,0,0,0.04), inset 0 1px 0 rgba(255,255,255,0.65)',
    backdropFilter: 'blur(22px) saturate(180%)',
  } satisfies React.CSSProperties,
  naturalPanel: {
    flex: '0 0 auto',
    minWidth: 0,
    width: '100%',
    minHeight: 40,
    boxSizing: 'border-box',
    background: 'rgba(255,255,255,0.72)',
    border: '0.5px solid rgba(60,60,67,0.10)',
    borderRadius: 10,
    overflow: 'hidden',
    boxShadow: '0 1px 2px rgba(0,0,0,0.04), inset 0 1px 0 rgba(255,255,255,0.65)',
    backdropFilter: 'blur(22px) saturate(180%)',
  } satisfies React.CSSProperties,
  row: {
    width: '100%',
    minWidth: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    padding: '9px 11px',
    boxSizing: 'border-box',
    borderBottom: '0.5px solid rgba(60,60,67,0.10)',
  } satisfies React.CSSProperties,
  muted: {
    minWidth: 0,
    flex: '1 1 auto',
    color: '#8e8e93',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  } satisfies React.CSSProperties,
};

export const requiredMark: React.CSSProperties = {
  color: '#ff3b30',
  marginLeft: 4,
  fontWeight: 700,
};

export const controlText = (overrides: React.CSSProperties = {}): React.CSSProperties => ({
  flex: overrides.flex,
  minWidth: 0,
  overflow: 'hidden',
  textOverflow: 'ellipsis',
  whiteSpace: 'nowrap',
  letterSpacing: 0,
  ...overrides,
});
