allowBuilds:
  electron: true
  esbuild: true
  msgpackr-extract: true
  protobufjs: set this to true or false
minimumReleaseAgeExclude:
  - vite@8.1.3
overrides:
  '@types/express-serve-static-core': 5.0.7
