import type React from 'react';

export const ios = {
  field: {
    width: '100%',
    height: '100%',
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 7,
    padding: '4px 2px',
    boxSizing: 'border-box',
    overflow: 'hidden',
  } satisfies React.CSSProperties,
  label: {
    flex: '0 0 auto',
    minWidth: 0,
    fontSize: 13,
    lineHeight: 1.3,
    fontWeight: 600,
    color: 'var(--text)',
    letterSpacing: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  } satisfies React.CSSProperties,
  control: {
    flex: '0 0 auto',
    minWidth: 0,
    minHeight: 36,
    width: '100%',
    maxWidth: '100%',
    height: 36,
    padding: '0 11px',
    border: '1px solid var(--line)',
    borderRadius: 9,
    background: 'var(--panel)',
    color: 'var(--text)',
    fontSize: 14,
    lineHeight: 1.25,
    outline: 'none',
    boxSizing: 'border-box',
    boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.45)',
  } satisfies React.CSSProperties,
  fillControl: {
    flex: '1 1 auto',
    minWidth: 0,
    minHeight: 0,
    width: '100%',
    height: '100%',
    padding: '12px 14px',
    border: '1px solid var(--line)',
    borderRadius: 10,
    background: 'var(--panel)',
    color: 'var(--text)',
    fontSize: 14,
    lineHeight: 1.35,
    outline: 'none',
    boxSizing: 'border-box',
    boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.45)',
  } satisfies React.CSSProperties,
  glass: {
    flex: '1 1 0',
    minWidth: 0,
    minHeight: 0,
    width: '100%',
    height: '100%',
    boxSizing: 'border-box',
    background: 'var(--panel)',
    border: '1px solid var(--line)',
    borderRadius: 12,
    overflow: 'hidden',
    boxShadow: 'var(--shadow-sm)',
  } satisfies React.CSSProperties,
  naturalPanel: {
    flex: '0 0 auto',
    minWidth: 0,
    width: '100%',
    minHeight: 40,
    boxSizing: 'border-box',
    background: 'var(--panel)',
    border: '1px solid var(--line)',
    borderRadius: 12,
    overflow: 'hidden',
    boxShadow: 'var(--shadow-sm)',
  } satisfies React.CSSProperties,
  row: {
    width: '100%',
    minWidth: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    padding: '10px 12px',
    boxSizing: 'border-box',
    borderBottom: '0.5px solid rgba(60,60,67,0.10)',
  } satisfies React.CSSProperties,
  muted: {
    minWidth: 0,
    flex: '1 1 auto',
    color: '#64748b',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  } satisfies React.CSSProperties,
};

export const requiredMark: React.CSSProperties = {
  color: '#ff3b30',
  marginLeft: 4,
  fontWeight: 700,
};

export const controlText = (overrides: React.CSSProperties = {}): React.CSSProperties => ({
  flex: overrides.flex,
  minWidth: 0,
  overflow: 'hidden',
  textOverflow: 'ellipsis',
  whiteSpace: 'nowrap',
  letterSpacing: 0,
  ...overrides,
});
