import { Router } from 'express';
import multer from 'multer';
import JSZip from 'jszip';
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'fs';
import { join, relative, resolve } from 'path';
import { PROJECTS_DIR, SERVER_DATA_DIR } from '../config/paths';
const router = Router(); const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 500 * 1024 * 1024 } });
function addDirectory(zip: JSZip, root: string, prefix: string) { if (!existsSync(root)) return; const walk = (dir: string) => readdirSync(dir, { withFileTypes: true }).forEach((entry) => { const path = join(dir, entry.name); if (entry.isDirectory()) walk(path); else if (!/\/exports\//.test(path)) zip.file(`${prefix}/${relative(root, path).replaceAll('\\', '/')}`, readFileSync(path)); }); walk(root); }
router.get('/export', async (_req, res) => { const zip = new JSZip(); addDirectory(zip, PROJECTS_DIR, 'projects'); addDirectory(zip, SERVER_DATA_DIR, 'server-data'); zip.file('backup.json', JSON.stringify({ format: 'formflow-backup', version: 1, createdAt: new Date().toISOString() }, null, 2)); const data = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' }); res.setHeader('Content-Type', 'application/zip'); res.setHeader('Content-Disposition', `attachment; filename="formflow-backup-${new Date().toISOString().slice(0,10)}.zip"`); res.send(data); });
router.post('/restore', upload.single('backup'), async (req, res) => { try { if (!req.file) return res.status(400).json({ error: '缺少备份文件' }); const zip = await JSZip.loadAsync(req.file.buffer); const manifest = zip.file('backup.json'); if (!manifest || JSON.parse(await manifest.async('string')).format !== 'formflow-backup') return res.status(400).json({ error: '无效备份格式' }); let restored = 0; for (const [name, entry] of Object.entries(zip.files)) { if (entry.dir || name === 'backup.json' || name.includes('..')) continue; const [prefix, ...parts] = name.split('/'); const root = prefix === 'projects' ? PROJECTS_DIR : prefix === 'server-data' ? SERVER_DATA_DIR : null; if (!root) continue; const target = resolve(root, ...parts); if (!target.startsWith(resolve(root))) throw new Error('备份路径越界'); mkdirSync(join(target, '..'), { recursive: true }); writeFileSync(target, await entry.async('nodebuffer')); restored += 1; } res.json({ success: true, restored }); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message : String(error) }); } });
export { router as backupRouter };
