import type { BehaviorEventDocEntry } from './types';
import { createEventDoc } from './shared';

export const controlEventDocs: BehaviorEventDocEntry[] = [
  createEventDoc({
    id: 'control:onChange',
    eventName: 'onChange',
    slug: 'change',
    title: '控件值变更',
    category: '控件运行时事件',
    scope: 'control',
    summary: '控件值发生变化时触发，是表单联动最常见的入口。',
    triggerWhen: '字段值写入运行时上下文后立即触发。',
    detailType: '{ previousValue: CurrentEventValue; value: CurrentEventValue; source?: string }',
    detailFields: [
      { name: 'detail.previousValue', type: 'CurrentEventValue', description: '变更前的旧值。' },
      { name: 'detail.value', type: 'CurrentEventValue', description: '当前写入的新值。' },
      { name: 'detail.source', type: 'string | undefined', description: '值来源，例如用户输入、代码更新。' },
    ],
    referenceShortcuts: [
      { path: 'ctx.detail.previousValue', description: '事件明细中的旧值。' },
      { path: 'ctx.detail.value', description: '事件明细中的新值。' },
      { path: 'ctx.detail.source', description: '本次变更来源。' },
    ],
    tags: ['联动', '数据操作', 'UI交互'],
    suggestions: ['需要差异判断时优先用 ctx.previousValue 或 ctx.detail.previousValue，而不是重新自己缓存旧值。'],
    examples: [
      { title: '变化后同步摘要', code: "await ctx.setValue('summary', `${ctx.detail.previousValue || ''} → ${ctx.value || ''}`);" },
      { title: '变化后禁用关联字段', code: "await ctx.setDisabled('remark', !ctx.value);" },
    ],
    relatedEvents: ['onBlur', 'onReset', 'onSubmit'],
  }),
  createEventDoc({
    id: 'control:onBlur',
    eventName: 'onBlur',
    slug: 'blur',
    title: '控件失焦',
    category: '控件运行时事件',
    scope: 'control',
    summary: '控件失去焦点时触发，常用于输入完成后的轻量校验。',
    triggerWhen: '控件从聚焦状态切换到失焦状态后触发。',
    detailType: '{ relatedTarget?: string; touched: boolean }',
    detailFields: [
      { name: 'detail.relatedTarget', type: 'string | undefined', description: '下一个聚焦目标的标识。' },
      { name: 'detail.touched', type: 'boolean', description: '当前字段是否已被操作。' },
    ],
    referenceShortcuts: [
      { path: 'ctx.detail.touched', description: '字段是否已被操作。' },
      { path: 'ctx.detail.relatedTarget', description: '下一个聚焦控件。' },
    ],
    tags: ['校验', '格式化', 'UI交互'],
    suggestions: ['适合 trim、格式标准化和单字段校验，不适合触发大规模流程。'],
    examples: [
      { title: '失焦自动 trim', code: "await ctx.setValue(ctx.field, String(ctx.value || '').trim());" },
      { title: '失焦格式化手机号', code: "const phone = String(ctx.value || '').replace(/\\D/g, '');\nawait ctx.setValue(ctx.field, phone);" },
    ],
    relatedEvents: ['onFocus', 'onChange'],
  }),
  createEventDoc({
    id: 'control:onFocus',
    eventName: 'onFocus',
    slug: 'focus',
    title: '控件聚焦',
    category: '控件运行时事件',
    scope: 'control',
    summary: '控件获得焦点时触发，适合展示帮助信息或做懒加载。',
    triggerWhen: '控件进入聚焦状态时触发。',
    detailType: '{ relatedTarget?: string }',
    detailFields: [
      { name: 'detail.relatedTarget', type: 'string | undefined', description: '上一个聚焦目标的标识。' },
    ],
    referenceShortcuts: [
      { path: 'ctx.detail.relatedTarget', description: '上一个聚焦控件。' },
    ],
    tags: ['提示', 'UI交互', '预加载'],
    suggestions: ['更适合做提示和预加载，不建议在焦点进入时直接修改当前字段值。'],
    examples: [
      { title: '聚焦时打印日志', code: "ctx.console.log('focus field', ctx.field, ctx.detail.relatedTarget);" },
      { title: '聚焦时展示帮助', code: "ctx.showMessage('请输入11位手机号', 'info');" },
    ],
    relatedEvents: ['onBlur'],
  }),
  createEventDoc({
    id: 'control:onClick',
    eventName: 'onClick',
    slug: 'click',
    title: '控件点击',
    category: '控件运行时事件',
    scope: 'control',
    summary: '按钮、图片、标签等可点击控件的点击事件。',
    triggerWhen: '控件收到点击交互时触发。',
    detailType: '{ x?: number; y?: number; button?: number; source?: string }',
    detailFields: [
      { name: 'detail.x', type: 'number | undefined', description: '点击横坐标。' },
      { name: 'detail.y', type: 'number | undefined', description: '点击纵坐标。' },
      { name: 'detail.button', type: 'number | undefined', description: '鼠标按键编号。' },
      { name: 'detail.source', type: 'string | undefined', description: '点击来源说明。' },
    ],
    referenceShortcuts: [
      { path: 'ctx.detail.x', description: '点击横坐标。' },
      { path: 'ctx.detail.y', description: '点击纵坐标。' },
      { path: 'ctx.detail.button', description: '鼠标按键编号。' },
    ],
    tags: ['提交', '数据操作', 'UI交互', '流程调用'],
    suggestions: ['按钮点击里优先显式调用 runConfiguredWorkflow 或 runWorkflow，行为更可控。', '如果只是把结果回填到同一表单控件，优先用 ctx.controls 直接赋值。'],
    examples: [
      { title: '点击后执行已绑定流程', code: 'await ctx.runConfiguredWorkflow({ value: ctx.value });' },
      { title: '把流程结果写到表格控件', code: "const result = await ctx.runConfiguredWorkflow();\nctx.controls.resultTable.value = result.nodeResults.get('filter')?.outputs.result || [];" },
    ],
    relatedEvents: ['onSubmit', 'onTabChange'],
  }),
  createEventDoc({
    id: 'control:onSubmit',
    eventName: 'onSubmit',
    slug: 'control-submit',
    title: '表单提交',
    category: '控件运行时事件',
    scope: 'control',
    summary: '表单提交动作触发时的控件运行时事件。',
    triggerWhen: '用户触发提交、运行时进入提交流程时触发。',
    detailType: '{ valid?: boolean; errors?: Record<string, string>; submitter?: string }',
    detailFields: [
      { name: 'detail.valid', type: 'boolean | undefined', description: '当前表单校验是否通过。' },
      { name: 'detail.errors', type: 'Record<string, string> | undefined', description: '字段级错误集合。' },
      { name: 'detail.submitter', type: 'string | undefined', description: '触发提交的按钮或组件标识。' },
    ],
    referenceShortcuts: [
      { path: 'ctx.detail.valid', description: '表单是否校验通过。' },
      { path: 'ctx.detail.errors', description: '字段校验错误对象。' },
      { path: 'ctx.changedFields', description: '本次提交涉及的变更字段。' },
    ],
    tags: ['提交', '校验', '数据操作'],
    suggestions: ['提交事件里优先读取 changedFields 与 detail.errors，避免重复计算差异和错误集合。'],
    examples: [
      { title: '提交前打印变化字段', code: "ctx.console.log('changed fields', ctx.changedFields, ctx.detail.errors);" },
      { title: '提交时检查校验结果', code: "if (!ctx.detail.valid) ctx.showMessage('请修正表单错误', 'error');" },
    ],
    relatedEvents: ['onChange', 'onReset'],
  }),
  createEventDoc({
    id: 'control:onReset',
    eventName: 'onReset',
    slug: 'reset',
    title: '表单重置',
    category: '控件运行时事件',
    scope: 'control',
    summary: '表单恢复到初始值时触发。',
    triggerWhen: '用户或宿主触发重置动作后触发。',
    detailType: '{ previousValues: EventFieldMap & Record<string, unknown> }',
    detailFields: [
      { name: 'detail.previousValues', type: 'EventFieldMap & Record<string, unknown>', description: '重置前的整份表单值快照。' },
    ],
    referenceShortcuts: [
      { path: 'ctx.detail.previousValues', description: '重置前的表单值。' },
    ],
    tags: ['状态控制', '生命周期', 'UI交互'],
    suggestions: ['如果需要恢复某些额外状态，优先比对 detail.previousValues 与 ctx.values。'],
    examples: [
      { title: '重置后记录日志', code: "ctx.console.log('reset from', ctx.detail.previousValues, 'to', ctx.values);" },
      { title: '重置后提示用户', code: "ctx.showMessage('表单已重置为初始状态', 'info');" },
    ],
    relatedEvents: ['onSubmit', 'onChange'],
  }),
  createEventDoc({
    id: 'control:onTabChange',
    eventName: 'onTabChange',
    slug: 'tab-change',
    title: '标签切换',
    category: '控件运行时事件',
    scope: 'control',
    summary: 'Tab 或多页容器切换时触发。',
    triggerWhen: '标签页索引发生变化时触发。',
    detailType: '{ index: number; previousIndex?: number; label: string }',
    detailFields: [
      { name: 'detail.index', type: 'number', description: '当前标签索引。' },
      { name: 'detail.previousIndex', type: 'number | undefined', description: '上一个标签索引。' },
      { name: 'detail.label', type: 'string', description: '当前标签名称。' },
    ],
    referenceShortcuts: [
      { path: 'ctx.detail.index', description: '当前标签索引。' },
      { path: 'ctx.detail.previousIndex', description: '上一个标签索引。' },
      { path: 'ctx.detail.label', description: '当前标签名称。' },
    ],
    tags: ['联动', 'UI交互', '状态控制'],
    suggestions: ['跨标签加载逻辑放这里最合适，避免每个标签内部自己再监听一次。'],
    examples: [
      { title: '切换页签时记录', code: "ctx.console.log('tab changed', ctx.detail.previousIndex, '->', ctx.detail.index, ctx.detail.label);" },
      { title: '特定页签启用按钮', code: "if (ctx.detail.label === '审批') await ctx.setDisabled('approveBtn', false);" },
    ],
    relatedEvents: ['onClick'],
  }),
  createEventDoc({
    id: 'control:onRowClick',
    eventName: 'onRowClick',
    slug: 'row-click',
    title: '表格行点击',
    category: '控件运行时事件',
    scope: 'control',
    summary: '点击表格某一行时触发，适合联动详情面板或子表单。',
    triggerWhen: '表格行被点击并完成命中计算后触发。',
    detailType: '{ rowIndex: number; row?: Record<string, unknown>; columnKey?: string }',
    detailFields: [
      { name: 'detail.rowIndex', type: 'number', description: '点击行索引。' },
      { name: 'detail.row', type: 'Record<string, unknown> | undefined', description: '点击行的完整数据。' },
      { name: 'detail.columnKey', type: 'string | undefined', description: '命中的列键。' },
    ],
    referenceShortcuts: [
      { path: 'ctx.detail.rowIndex', description: '点击的行索引。' },
      { path: 'ctx.detail.row', description: '点击行数据。' },
      { path: 'ctx.detail.columnKey', description: '点击的列键。' },
    ],
    tags: ['联动', 'UI交互', '数据操作'],
    suggestions: ['如果要把表格行同步到表单字段，优先从 detail.row 读取原始值。'],
    examples: [
      { title: '点击行后写入当前客户', code: "if (ctx.detail.row?.customerName) await ctx.setValue('customerName', ctx.detail.row.customerName);" },
      { title: '点击行后显示详情', code: "await ctx.setVisible('detailPanel', true);" },
    ],
    relatedEvents: ['onChange', 'onTabChange'],
  }),
  createEventDoc({
    id: 'control:onDrop',
    eventName: 'onDrop',
    slug: 'drop',
    title: '拖放',
    category: '控件运行时事件',
    scope: 'control',
    summary: '文件或文本拖放到控件时触发。',
    triggerWhen: '拖放动作落到支持接收的控件上后触发。',
    detailType: '{ files: File[]; types: string[]; text?: string }',
    detailFields: [
      { name: 'detail.files', type: 'File[]', description: '拖入的文件列表。' },
      { name: 'detail.types', type: 'string[]', description: '拖放数据类型列表。' },
      { name: 'detail.text', type: 'string | undefined', description: '拖入的纯文本内容。' },
    ],
    referenceShortcuts: [
      { path: 'ctx.detail.files', description: '拖入的文件列表。' },
      { path: 'ctx.detail.types', description: '拖放数据类型。' },
      { path: 'ctx.detail.text', description: '拖放文本内容。' },
    ],
    tags: ['数据操作', 'UI交互', '文件处理'],
    suggestions: ['拖放事件里优先先判断 files 与 text，再决定走上传流程还是文本解析流程。'],
    examples: [
      { title: '拖入文本后写入字段', code: "if (ctx.detail.text) await ctx.setValue(ctx.field, ctx.detail.text);" },
      { title: '拖入文件后提示', code: "ctx.showMessage(`已拖入 ${ctx.detail.files?.length || 0} 个文件`, 'info');" },
    ],
    relatedEvents: ['onChange', 'onClick'],
  }),
];
