import type { BehaviorEventDocEntry } from './types';
import { createEventDoc } from './shared';

export const controlEventDocs: BehaviorEventDocEntry[] = [
  createEventDoc({
    id: 'control:onChange',
    eventName: 'onChange',
    slug: 'change',
    title: '控件值变更',
    category: '控件运行时事件',
    scope: 'control',
    summary: '控件值发生变化时触发，是表单联动最常见的入口。',
    triggerWhen: '字段值写入运行时上下文后立即触发。',
    detailType: '{ previousValue: CurrentEventValue; value: CurrentEventValue; source?: string }',
    detailFields: [
      { name: 'detail.previousValue', type: 'CurrentEventValue', description: '变更前的旧值。' },
      { name: 'detail.value', type: 'CurrentEventValue', description: '当前写入的新值。' },
      { name: 'detail.source', type: 'string | undefined', description: '值来源，例如用户输入、代码更新。' },
    ],
    referenceShortcuts: [
      { path: 'ctx.detail.previousValue', description: '事件明细中的旧值。' },
      { path: 'ctx.detail.value', description: '事件明细中的新值。' },
      { path: 'ctx.detail.source', description: '本次变更来源。' },
    ],
    tags: ['联动', '数据操作', 'UI交互'],
    suggestions: [
      '需要差异判断时优先用 ctx.previousValue 或 ctx.detail.previousValue，而不是重新自己缓存旧值。',
      '使用 field 变量判断触发源，避免为每个字段单独写事件。',
      '复杂联动逻辑建议使用行为模板库中的预置模板。',
    ],
    examples: [
      { title: '变化后同步摘要', code: "await setValue('summary', `${detail.previousValue || ''} → ${value || ''}`);" },
      { title: '变化后禁用关联字段', code: "await setDisabled('remark', !value);" },
      { title: '按字段分别处理', code: "if (field === '数量' || field === '单价') {\n  const qty = Number(controls.数量.value) || 0;\n  const price = Number(controls.单价.value) || 0;\n  await setValue('总价', qty * price);\n}" },
      { title: '联动显示隐藏', code: "if (field === '部门') {\n  controls.技术栈.visible = (value === '技术部');\n  controls.销售区域.visible = (value === '销售部');\n}" },
    ],
    relatedEvents: ['onBlur', 'onReset', 'onSubmit'],
  }),
  createEventDoc({
    id: 'control:onBlur',
    eventName: 'onBlur',
    slug: 'blur',
    title: '控件失焦',
    category: '控件运行时事件',
    scope: 'control',
    summary: '控件失去焦点时触发，常用于输入完成后的轻量校验。',
    triggerWhen: '控件从聚焦状态切换到失焦状态后触发。',
    detailType: '{ relatedTarget?: string; touched: boolean }',
    detailFields: [
      { name: 'detail.relatedTarget', type: 'string | undefined', description: '下一个聚焦目标的标识。' },
      { name: 'detail.touched', type: 'boolean', description: '当前字段是否已被操作。' },
    ],
    referenceShortcuts: [
      { path: 'ctx.detail.touched', description: '字段是否已被操作。' },
      { path: 'ctx.detail.relatedTarget', description: '下一个聚焦控件。' },
    ],
    tags: ['校验', '格式化', 'UI交互'],
    suggestions: [
      '适合 trim、格式标准化和单字段校验，不适合触发大规模流程。',
      '使用 field 变量判断是哪个字段失焦。',
      '校验失败时使用 showMessage 提示用户。',
    ],
    examples: [
      { title: '失焦自动 trim', code: "await setValue(field, String(value || '').trim());" },
      { title: '失焦格式化手机号', code: "const phone = String(value || '').replace(/\\D/g, '');\nawait setValue(field, phone);\nif (phone.length !== 11) showMessage('手机号应为11位', 'warning');" },
      { title: '失焦校验邮箱', code: "if (field === '邮箱') {\n  const email = String(value || '').trim();\n  if (email && !/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(email)) {\n    showMessage('邮箱格式不正确', 'warning');\n  }\n}" },
    ],
    relatedEvents: ['onFocus', 'onChange'],
  }),
  createEventDoc({
    id: 'control:onFocus',
    eventName: 'onFocus',
    slug: 'focus',
    title: '控件聚焦',
    category: '控件运行时事件',
    scope: 'control',
    summary: '控件获得焦点时触发，适合展示帮助信息或做懒加载。',
    triggerWhen: '控件进入聚焦状态时触发。',
    detailType: '{ relatedTarget?: string }',
    detailFields: [
      { name: 'detail.relatedTarget', type: 'string | undefined', description: '上一个聚焦目标的标识。' },
    ],
    referenceShortcuts: [
      { path: 'ctx.detail.relatedTarget', description: '上一个聚焦控件。' },
    ],
    tags: ['提示', 'UI交互', '预加载'],
    suggestions: [
      '更适合做提示和预加载，不建议在焦点进入时直接修改当前字段值。',
      '可以展示字段的输入格式要求或帮助信息。',
      '适合在聚焦时加载下拉选项等动态数据。',
    ],
    examples: [
      { title: '聚焦时打印日志', code: "PrintDebug('focus field', field, detail.relatedTarget);" },
      { title: '聚焦时展示帮助', code: "showMessage('请输入11位手机号', 'info');" },
      { title: '聚焦时加载选项', code: "if (field === '城市') {\n  // 动态加载城市选项\n  await runConfiguredWorkflow();\n}" },
    ],
    relatedEvents: ['onBlur'],
  }),
  createEventDoc({
    id: 'control:onClick',
    eventName: 'onClick',
    slug: 'click',
    title: '控件点击',
    category: '控件运行时事件',
    scope: 'control',
    summary: '按钮、图片、标签等可点击控件的点击事件。',
    triggerWhen: '控件收到点击交互时触发。',
    detailType: '{ x?: number; y?: number; button?: number; source?: string }',
    detailFields: [
      { name: 'detail.x', type: 'number | undefined', description: '点击横坐标。' },
      { name: 'detail.y', type: 'number | undefined', description: '点击纵坐标。' },
      { name: 'detail.button', type: 'number | undefined', description: '鼠标按键编号。' },
      { name: 'detail.source', type: 'string | undefined', description: '点击来源说明。' },
    ],
    referenceShortcuts: [
      { path: 'ctx.detail.x', description: '点击横坐标。' },
      { path: 'ctx.detail.y', description: '点击纵坐标。' },
      { path: 'ctx.detail.button', description: '鼠标按键编号。' },
    ],
    tags: ['提交', '数据操作', 'UI交互', '流程调用'],
    suggestions: [
      '按钮点击里优先显式调用 runConfiguredWorkflow 或 runWorkflow，行为更可控。',
      '如果只是把结果回填到同一表单控件，优先用 controls 直接赋值。',
      '复杂业务逻辑建议通过流程实现，而不是在按钮事件中写大量代码。',
    ],
    examples: [
      { title: '点击后执行已绑定流程', code: 'await runConfiguredWorkflow({ value });' },
      { title: '把流程结果写到表格控件', code: "const result = await runConfiguredWorkflow();\ncontrols.resultTable.value = result.nodeResults.get('filter')?.outputs.result || [];" },
      { title: '点击前校验', code: "const check = await requireFields(['查询条件']);\nif (!check.valid) return;\nawait runConfiguredWorkflow();" },
      { title: '点击后切换页签', code: "await ctx.switchTab('结果');" },
    ],
    relatedEvents: ['onSubmit', 'onTabChange'],
  }),
  createEventDoc({
    id: 'control:onSubmit',
    eventName: 'onSubmit',
    slug: 'control-submit',
    title: '表单提交',
    category: '控件运行时事件',
    scope: 'control',
    summary: '表单提交动作触发时的控件运行时事件。',
    triggerWhen: '用户触发提交、运行时进入提交流程时触发。',
    detailType: '{ valid?: boolean; errors?: Record<string, string>; submitter?: string }',
    detailFields: [
      { name: 'detail.valid', type: 'boolean | undefined', description: '当前表单校验是否通过。' },
      { name: 'detail.errors', type: 'Record<string, string> | undefined', description: '字段级错误集合。' },
      { name: 'detail.submitter', type: 'string | undefined', description: '触发提交的按钮或组件标识。' },
    ],
    referenceShortcuts: [
      { path: 'ctx.detail.valid', description: '表单是否校验通过。' },
      { path: 'ctx.detail.errors', description: '字段校验错误对象。' },
      { path: 'ctx.changedFields', description: '本次提交涉及的变更字段。' },
    ],
    tags: ['提交', '校验', '数据操作'],
    suggestions: [
      '提交事件里优先读取 changedFields 与 detail.errors，避免重复计算差异和错误集合。',
      '校验失败时可以滚动到错误字段帮助用户定位。',
      '记录提交日志有助于问题排查。',
    ],
    examples: [
      { title: '提交前打印变化字段', code: "PrintDebug('changed fields', changedFields, detail.errors);" },
      { title: '提交时检查校验结果', code: "if (!detail.valid) {\n  showMessage('请修正表单错误', 'error');\n  return;\n}" },
      { title: '提交后记录日志', code: "PrintInfo('form submitted', {\n  submitter: detail.submitter,\n  changedFields,\n  timestamp: new Date().toISOString()\n});" },
    ],
    relatedEvents: ['onChange', 'onReset'],
  }),
  createEventDoc({
    id: 'control:onReset',
    eventName: 'onReset',
    slug: 'reset',
    title: '表单重置',
    category: '控件运行时事件',
    scope: 'control',
    summary: '表单恢复到初始值时触发。',
    triggerWhen: '用户或宿主触发重置动作后触发。',
    detailType: '{ previousValues: EventFieldMap & Record<string, unknown> }',
    detailFields: [
      { name: 'detail.previousValues', type: 'EventFieldMap & Record<string, unknown>', description: '重置前的整份表单值快照。' },
    ],
    referenceShortcuts: [
      { path: 'ctx.detail.previousValues', description: '重置前的表单值。' },
    ],
    tags: ['状态控制', '生命周期', 'UI交互'],
    suggestions: [
      '如果需要恢复某些额外状态，优先比对 detail.previousValues 与 ctx.values。',
      '重置后可能需要重新启用被禁用的字段。',
      '适合在重置后恢复 UI 状态。',
    ],
    examples: [
      { title: '重置后记录日志', code: "PrintDebug('reset from', detail.previousValues, 'to', values);" },
      { title: '重置后提示用户', code: "showMessage('表单已重置为初始状态', 'info');" },
      { title: '重置后恢复 UI 状态', code: "await setVisible('extraInfo', false);\nawait setDisabled('submitBtn', false);" },
    ],
    relatedEvents: ['onSubmit', 'onChange'],
  }),
  createEventDoc({
    id: 'control:onTabChange',
    eventName: 'onTabChange',
    slug: 'tab-change',
    title: '标签切换',
    category: '控件运行时事件',
    scope: 'control',
    summary: 'Tab 或多页容器切换时触发。',
    triggerWhen: '标签页索引发生变化时触发。',
    detailType: '{ index: number; previousIndex?: number; label: string }',
    detailFields: [
      { name: 'detail.index', type: 'number', description: '当前标签索引。' },
      { name: 'detail.previousIndex', type: 'number | undefined', description: '上一个标签索引。' },
      { name: 'detail.label', type: 'string', description: '当前标签名称。' },
    ],
    referenceShortcuts: [
      { path: 'ctx.detail.index', description: '当前标签索引。' },
      { path: 'ctx.detail.previousIndex', description: '上一个标签索引。' },
      { path: 'ctx.detail.label', description: '当前标签名称。' },
    ],
    tags: ['联动', 'UI交互', '状态控制'],
    suggestions: [
      '跨标签加载逻辑放这里最合适，避免每个标签内部自己再监听一次。',
      '可以按标签名分别处理不同的逻辑。',
      '适合在切换标签时加载关联数据。',
    ],
    examples: [
      { title: '切换页签时记录', code: "PrintDebug('tab changed', detail.previousIndex, '->', detail.index, detail.label);" },
      { title: '特定页签启用按钮', code: "if (detail.label === '审批') await setDisabled('approveBtn', false);" },
      { title: '切换时加载数据', code: "if (detail.label === '详细信息') {\n  await runConfiguredWorkflow();\n}" },
    ],
    relatedEvents: ['onClick'],
  }),
  createEventDoc({
    id: 'control:onRowClick',
    eventName: 'onRowClick',
    slug: 'row-click',
    title: '表格行点击',
    category: '控件运行时事件',
    scope: 'control',
    summary: '点击表格某一行时触发，适合联动详情面板或子表单。',
    triggerWhen: '表格行被点击并完成命中计算后触发。',
    detailType: '{ rowIndex: number; row?: Record<string, unknown>; columnKey?: string }',
    detailFields: [
      { name: 'detail.rowIndex', type: 'number', description: '点击行索引。' },
      { name: 'detail.row', type: 'Record<string, unknown> | undefined', description: '点击行的完整数据。' },
      { name: 'detail.columnKey', type: 'string | undefined', description: '命中的列键。' },
    ],
    referenceShortcuts: [
      { path: 'ctx.detail.rowIndex', description: '点击的行索引。' },
      { path: 'ctx.detail.row', description: '点击行数据。' },
      { path: 'ctx.detail.columnKey', description: '点击的列键。' },
    ],
    tags: ['联动', 'UI交互', '数据操作'],
    suggestions: [
      '如果要把表格行同步到表单字段，优先从 detail.row 读取原始值。',
      '可以在这里加载关联数据或显示详情面板。',
      '适合实现主从表联动。',
    ],
    examples: [
      { title: '点击行后写入当前客户', code: "if (detail.row?.customerName) await setValue('customerName', detail.row.customerName);" },
      { title: '点击行后显示详情', code: "await setVisible('detailPanel', true);" },
      { title: '点击行后加载关联数据', code: "if (detail.row?.订单号) {\n  const details = ctx.findRows('订单明细', { 订单号: detail.row.订单号 });\n  controls.detailTable.value = details;\n}" },
    ],
    relatedEvents: ['onChange', 'onTabChange'],
  }),
  createEventDoc({
    id: 'control:onDrop',
    eventName: 'onDrop',
    slug: 'drop',
    title: '拖放',
    category: '控件运行时事件',
    scope: 'control',
    summary: '文件或文本拖放到控件时触发。',
    triggerWhen: '拖放动作落到支持接收的控件上后触发。',
    detailType: '{ files: File[]; types: string[]; text?: string }',
    detailFields: [
      { name: 'detail.files', type: 'File[]', description: '拖入的文件列表。' },
      { name: 'detail.types', type: 'string[]', description: '拖放数据类型列表。' },
      { name: 'detail.text', type: 'string | undefined', description: '拖入的纯文本内容。' },
    ],
    referenceShortcuts: [
      { path: 'ctx.detail.files', description: '拖入的文件列表。' },
      { path: 'ctx.detail.types', description: '拖放数据类型。' },
      { path: 'ctx.detail.text', description: '拖放文本内容。' },
    ],
    tags: ['数据操作', 'UI交互', '文件处理'],
    suggestions: [
      '拖放事件里优先先判断 files 与 text，再决定走上传流程还是文本解析流程。',
      '可以在这里实现文件上传或文本导入功能。',
      '注意处理文件类型和大小的校验。',
    ],
    examples: [
      { title: '拖入文本后写入字段', code: "if (detail.text) await setValue(field, detail.text);" },
      { title: '拖入文件后提示', code: "showMessage(`已拖入 ${detail.files?.length || 0} 个文件`, 'info');" },
      { title: '拖入文件后处理', code: "if (detail.files?.length) {\n  const file = detail.files[0];\n  showMessage(`正在处理文件: ${file.name}`, 'info');\n  // 触发文件上传流程\n  await runConfiguredWorkflow();\n}" },
    ],
    relatedEvents: ['onChange', 'onClick'],
  }),
];
