import type { BehaviorEventDocEntry } from './types';
import { createEventDoc } from './shared';

export const scriptEventDocs: BehaviorEventDocEntry[] = [
  createEventDoc({
    id: 'script:onFormLoad',
    eventName: 'onFormLoad',
    slug: 'form-load',
    title: '表单加载',
    category: '行为脚本事件',
    scope: 'script',
    summary: '表单初次装载完成后触发，适合填充默认值和初始化 UI 状态。',
    triggerWhen: '项目测试运行或行为脚本宿主完成表单初始化后触发。此时控件已渲染但用户尚未操作。',
    detailFields: [],
    tags: ['初始化', '生命周期', '默认值'],
    suggestions: [
      '优先在这里做默认值填充和首屏提示，不要把依赖用户输入的逻辑也塞进初始化。',
      '如果需要异步加载数据再填充，考虑使用 onFormReady 事件。',
      '避免在这里触发流程调用，因为表单可能还未完全就绪。',
    ],
    examples: [
      { title: '初始化默认值', code: "if (!getValue('status')) await setValue('status', '草稿');" },
      { title: '设置当前日期', code: "await setValue('createdAt', new Date().toISOString().slice(0, 10));" },
      { title: '根据用户角色显示字段', code: "const role = getValue('userRole');\nawait setVisible('adminPanel', role === '管理员');\nawait setVisible('auditLog', role !== '普通用户');" },
      { title: '从数据表加载默认值', code: "const defaults = ctx.findRow('系统配置', { key: '默认值' });\nif (defaults) await ctx.fillForm(defaults);" },
    ],
    relatedEvents: ['onFormReady', 'onRowLoad'],
  }),
  createEventDoc({
    id: 'script:onRowLoad',
    eventName: 'onRowLoad',
    slug: 'row-load',
    title: '数据行加载',
    category: '行为脚本事件',
    scope: 'script',
    summary: '切换到某条数据记录或重新装载当前行时触发，适合做行级状态恢复。',
    triggerWhen: '测试运行中切换当前数据行或刷新当前行时触发。此时表单字段已填充为新行数据。',
    detailFields: [],
    tags: ['初始化', '联动', '状态控制', '生命周期'],
    suggestions: [
      '适合做行级联动和状态恢复，例如根据行数据控制字段显隐。',
      '使用 getValue 读取当前行数据，用 setVisible/setDisabled 控制 UI。',
      '避免在这里做大量计算，会影响行切换的响应速度。',
    ],
    examples: [
      { title: '按行状态禁用字段', code: "await setDisabled('approvalComment', getValue('status') !== '待审批');" },
      { title: '按条件隐藏组件', code: "await setVisible('extraInfo', getValue('level') === '高级');" },
      { title: '加载关联数据', code: "const dept = getValue('部门');\nif (dept) {\n  const members = ctx.findRows('员工信息', { 部门: dept });\n  showMessage(`当前部门有 ${members.length} 名成员`, 'info');\n}" },
    ],
    relatedEvents: ['onFormLoad', 'onDataImport'],
  }),
  createEventDoc({
    id: 'script:onFieldChange',
    eventName: 'onFieldChange',
    slug: 'field-change',
    title: '字段变更',
    category: '行为脚本事件',
    scope: 'script',
    summary: '任意字段值发生变化后触发，是表单联动最常用的入口。',
    triggerWhen: '字段编辑完成并提交最新值后触发。可通过 field 变量判断是哪个字段发生了变化。',
    detailFields: [],
    tags: ['联动', '数据操作', '计算'],
    suggestions: [
      '把依赖单字段变化的计算放在这里；多字段提交前校验放到 onBeforeSubmit 或 onSubmit。',
      '使用 field 变量判断触发源，避免为每个字段单独写事件。',
      '复杂联动逻辑建议使用行为模板库中的预置模板。',
    ],
    examples: [
      { title: '同步摘要字段', code: "await setValue('summary', `${getValue('customerName') || ''} / ${getValue('region') || ''}`);" },
      { title: '联动禁用字段', code: "await setDisabled('endDate', !getValue('startDate'));" },
      { title: '按字段名分别处理', code: "if (field === '数量' || field === '单价') {\n  const qty = Number(getValue('数量')) || 0;\n  const price = Number(getValue('单价')) || 0;\n  await setValue('总价', qty * price);\n}" },
      { title: '联动显示隐藏', code: "if (field === '部门') {\n  await setVisible('技术栈', value === '技术部');\n  await setVisible('销售区域', value === '销售部');\n}" },
    ],
    relatedEvents: ['onValueChange', 'onFieldBlur', 'onValidate'],
  }),
  createEventDoc({
    id: 'script:onFieldBlur',
    eventName: 'onFieldBlur',
    slug: 'field-blur',
    title: '字段失焦',
    category: '行为脚本事件',
    scope: 'script',
    summary: '字段失去焦点时触发，适合做轻量校验和格式化。',
    triggerWhen: '输入焦点离开字段后触发。适合在用户完成输入后进行格式化或校验。',
    detailFields: [],
    tags: ['校验', '格式化', 'UI交互'],
    suggestions: [
      '不要在这里做耗时请求；如果需要远程校验，建议先提示加载状态。',
      '适合 trim、格式标准化和单字段校验。',
      '使用 field 变量判断是哪个字段失焦。',
    ],
    examples: [
      { title: '自动去空格', code: "const trimmed = String(getValue('customerName') || '').trim(); await setValue('customerName', trimmed);" },
      { title: '失焦校验必填', code: "if (!getValue('email')) showMessage('请输入邮箱地址', 'warning');" },
      { title: '格式化手机号', code: "if (field === '手机号') {\n  const phone = String(value || '').replace(/\\D/g, '');\n  await setValue('手机号', phone);\n  if (phone.length !== 11) showMessage('手机号应为11位', 'warning');\n}" },
    ],
    relatedEvents: ['onFieldFocus', 'onFieldChange'],
  }),
  createEventDoc({
    id: 'script:onFieldFocus',
    eventName: 'onFieldFocus',
    slug: 'field-focus',
    title: '字段聚焦',
    category: '行为脚本事件',
    scope: 'script',
    summary: '字段获得焦点时触发，适合做辅助提示和预加载。',
    triggerWhen: '输入焦点进入某个字段时触发。',
    detailFields: [],
    tags: ['提示', 'UI交互', '预加载'],
    suggestions: ['适合展示帮助文案，不适合在这里强改用户输入。'],
    examples: [
      { title: '展示帮助', code: "showMessage('请输入完整客户名称', 'info');" },
      { title: '聚焦时滚动到顶部', code: "await scrollToField(field);" },
    ],
    relatedEvents: ['onFieldBlur'],
  }),
  createEventDoc({
    id: 'script:onButtonClick',
    eventName: 'onButtonClick',
    slug: 'button-click',
    title: '按钮点击',
    category: '行为脚本事件',
    scope: 'script',
    summary: '用户点击行为按钮时触发，是调用流程和执行复杂操作的主要入口。',
    triggerWhen: '按钮类组件点击后触发。适合执行提交前检查、切换页签或显式调用流程。',
    detailFields: [],
    tags: ['提交', '数据操作', 'UI交互', '流程调用'],
    suggestions: [
      '适合执行提交前检查、切换页签或显式调用流程。',
      '如果只是同一表单内的轻量联动，优先直接使用 controls.<控件名>。',
      '复杂业务逻辑建议通过 runConfiguredWorkflow 调用流程。',
    ],
    examples: [
      { title: '点击后提示', code: "showMessage('按钮事件已触发', 'success');" },
      { title: '点击后把结果写进表格', code: "const result = await runConfiguredWorkflow();\nconst rows = result.nodeResults.get('filter')?.outputs.result || [];\ncontrols.resultTable.value = rows;" },
      { title: '点击后切换页签', code: "await ctx.switchTab('结果');" },
      { title: '点击前校验', code: "const check = await ctx.requireFields(['查询条件']);\nif (!check.valid) return;\nawait runConfiguredWorkflow();" },
    ],
    relatedEvents: ['onSubmit', 'onBeforeSubmit'],
  }),
  createEventDoc({
    id: 'script:onValidate',
    eventName: 'onValidate',
    slug: 'validate',
    title: '校验',
    category: '行为脚本事件',
    scope: 'script',
    summary: '进入表单校验阶段时触发，适合收口跨字段校验逻辑。',
    triggerWhen: '提交前或显式调用校验时触发。校验失败会阻止提交。',
    detailFields: [],
    tags: ['校验', '提示', '提交'],
    suggestions: [
      '在这里收口跨字段校验逻辑，并用 showMessage 明确给出失败原因。',
      '单字段校验建议在 onFieldBlur 中处理，这里只处理跨字段关联校验。',
      '校验失败时使用 return 阻止后续逻辑执行。',
    ],
    examples: [
      { title: '校验开始日期', code: "if (!getValue('startDate')) showMessage('请选择开始日期', 'warning');" },
      { title: '校验日期范围', code: "const start = getValue('startDate');\nconst end = getValue('endDate');\nif (start && end && start > end) showMessage('结束日期不能早于开始日期', 'error');" },
      { title: '批量必填校验', code: "const check = await ctx.requireFields(['姓名', '手机号']);\nif (!check.valid) {\n  showMessage(`请填写：${check.missingFields.join('、')}`, 'error');\n  return;\n}" },
    ],
    relatedEvents: ['onBeforeSubmit', 'onSubmit', 'onSubmitError'],
  }),
  createEventDoc({
    id: 'script:onSubmit',
    eventName: 'onSubmit',
    slug: 'submit',
    title: '提交',
    category: '行为脚本事件',
    scope: 'script',
    summary: '用户触发提交动作时执行，适合做最终校验和收口动作。',
    triggerWhen: '点击提交按钮或调用 ctx.submit() 后触发。这是提交流程的核心事件。',
    detailFields: [],
    tags: ['提交', '数据操作', '生命周期'],
    suggestions: [
      '把不可逆的副作用集中放在这里，避免字段级事件重复触发。',
      '提交前校验建议使用 requireFields 批量检查，比逐个判断更简洁。',
      '如果需要调用流程处理提交逻辑，在这里使用 runConfiguredWorkflow。',
    ],
    examples: [
      { title: '提交前补全时间', code: "await setValue('submittedAt', new Date().toISOString());" },
      { title: '提交前补全状态', code: "if (!getValue('status')) await setValue('status', '待审核');" },
      { title: '批量必填校验', code: "const check = await ctx.requireFields(['姓名', '手机号', '部门']);\nif (!check.valid) {\n  showMessage(`请填写：${check.missingFields.join('、')}`, 'error');\n  return;\n}" },
      { title: '提交前格式化数据', code: "const phone = String(getValue('手机号') || '').replace(/\\D/g, '');\nawait setValue('手机号', phone);\nconst name = String(getValue('姓名') || '').trim();\nawait setValue('姓名', name);" },
    ],
    relatedEvents: ['onBeforeSubmit', 'onSubmitSuccess', 'onSubmitError'],
  }),
  createEventDoc({
    id: 'script:onSubmitSuccess',
    eventName: 'onSubmitSuccess',
    slug: 'submit-success',
    title: '提交成功',
    category: '行为脚本事件',
    scope: 'script',
    summary: '提交成功后触发，适合清理状态、反馈提示和准备下一条录入。',
    triggerWhen: '提交流程成功完成后触发。此时数据已保存，可以安全清空临时字段。',
    detailFields: [],
    tags: ['提交', '提示', '状态控制', '生命周期'],
    suggestions: [
      '适合做跳转、清空临时字段和成功提示。',
      '连续录入场景下，使用 resetForm 重置表单并生成下一个编号。',
      '避免在这里做耗时操作，用户期望快速反馈。',
    ],
    examples: [
      { title: '成功提示', code: "showMessage('提交成功！数据已保存。', 'success');" },
      { title: '清空草稿字段', code: "await clearValues(['draft', 'tempNote']);" },
      { title: '连续录入重置', code: "const nextId = ctx.nextSequence('employees', '员工ID', { start: 1000 });\nawait ctx.resetForm({\n  clearFields: ['姓名', '手机号', '备注'],\n  defaults: { 员工ID: nextId, 状态: '草稿' },\n  focusField: '姓名',\n  message: '表单已重置，可继续录入。',\n});" },
      { title: '提交后切换到列表', code: "await ctx.switchTab('列表');\nawait ctx.showMessage('数据已保存，可在列表中查看。', 'success');" },
    ],
    relatedEvents: ['onSubmit', 'onSubmitError'],
  }),
  createEventDoc({
    id: 'script:onSubmitError',
    eventName: 'onSubmitError',
    slug: 'submit-error',
    title: '提交失败',
    category: '行为脚本事件',
    scope: 'script',
    summary: '提交失败后触发，适合记录错误和指导用户修正。',
    triggerWhen: '提交流程抛错或返回失败状态后触发。',
    detailFields: [],
    tags: ['提交', '提示', '校验'],
    suggestions: [
      '这里更适合兜底提示，不要再尝试自动重复提交。',
      '可以滚动到错误字段帮助用户快速定位问题。',
      '记录错误日志有助于问题排查。',
    ],
    examples: [
      { title: '失败提示', code: "showMessage('提交失败，请检查必填项', 'error');" },
      { title: '滚动到首个错误字段', code: "await scrollToField('customerName');" },
      { title: '记录错误日志', code: "PrintError('submit failed', field, value);\nshowMessage('提交失败，请稍后重试', 'error');" },
    ],
    relatedEvents: ['onSubmit', 'onValidate'],
  }),
  createEventDoc({
    id: 'script:onFormReady',
    eventName: 'onFormReady',
    slug: 'form-ready',
    title: '表单就绪',
    category: '行为脚本事件',
    scope: 'script',
    summary: '表单和依赖数据全部准备完成后触发，适合做异步初始化。',
    triggerWhen: '首屏数据与组件都可交互时触发。比 onFormLoad 晚，确保所有依赖已加载。',
    detailFields: [],
    tags: ['初始化', '生命周期', '提示'],
    suggestions: [
      '适合做依赖异步数据的初始化，而不是 onFormLoad 里的同步准备。',
      '如果需要调用流程加载数据，在这里执行比在 onFormLoad 更安全。',
      '适合展示欢迎提示或操作引导。',
    ],
    examples: [
      { title: '就绪提示', code: "showMessage('表单已准备就绪', 'info');" },
      { title: '就绪后聚焦首字段', code: "await focusField('customerName');" },
      { title: '就绪后加载远程数据', code: "const result = await runConfiguredWorkflow();\nif (result) showMessage('数据加载完成', 'success');" },
    ],
    relatedEvents: ['onFormLoad', 'onDataImport'],
  }),
  createEventDoc({
    id: 'script:onFormReset',
    eventName: 'onFormReset',
    slug: 'form-reset',
    title: '表单重置',
    category: '行为脚本事件',
    scope: 'script',
    summary: '表单被重置时触发，适合恢复 UI 状态和提示用户。',
    triggerWhen: '用户执行重置动作或宿主恢复初始值时触发。此时字段值已恢复为初始值。',
    detailFields: [],
    tags: ['状态控制', '生命周期', 'UI交互'],
    suggestions: [
      '适合恢复依赖值和提示用户，不要在这里再写回大量默认值。',
      '重置后可能需要重新启用被禁用的字段。',
      '与 onFormLoad 的区别：重置是用户主动操作，加载是系统初始化。',
    ],
    examples: [
      { title: '重置提示', code: "showMessage('表单已恢复初始值', 'info');" },
      { title: '重置后重新启用字段', code: "await setFieldState('comment', { disabled: false, visible: true });" },
      { title: '重置后恢复默认状态', code: "await setVisible('extraInfo', false);\nawait setDisabled('submitBtn', false);" },
    ],
    relatedEvents: ['onFormLoad', 'onValueChange'],
  }),
  createEventDoc({
    id: 'script:onBeforeSubmit',
    eventName: 'onBeforeSubmit',
    slug: 'before-submit',
    title: '提交前',
    category: '行为脚本事件',
    scope: 'script',
    summary: '真正提交前的最后一道钩子，适合做最后检查和参数整理。',
    triggerWhen: '进入提交动作，但尚未发出最终提交请求前触发。此时可以阻止提交。',
    detailFields: [],
    tags: ['提交', '数据操作', '校验'],
    suggestions: [
      '这里适合整理提交 payload，而不是做大量 UI 联动。',
      '使用 return 可以阻止提交继续执行。',
      '与 onSubmit 的区别：这里在提交流程开始前触发，onSubmit 在提交流程中触发。',
    ],
    examples: [
      { title: '补全审批人', code: "if (!getValue('reviewer')) await setValue('reviewer', '系统默认审批人');" },
      { title: '校验后阻止提交', code: "if (!getValue('agree')) {\n  showMessage('请先勾选同意协议', 'error');\n  return;\n}" },
      { title: '补全提交时间戳', code: "await setValue('submittedAt', new Date().toISOString());\nawait setValue('submittedBy', getValue('currentUser') || '系统');" },
    ],
    relatedEvents: ['onValidate', 'onSubmit'],
  }),
  createEventDoc({
    id: 'script:onFieldKeyDown',
    eventName: 'onFieldKeyDown',
    slug: 'field-key-down',
    title: '字段按键',
    category: '行为脚本事件',
    scope: 'script',
    summary: '字段按键时触发，适合快捷键响应和实时搜索。',
    triggerWhen: '输入控件收到键盘按下事件时触发。可通过 detail.key 判断按键。',
    detailFields: [],
    tags: ['UI交互', '快捷键', '数据操作'],
    suggestions: [
      '只放轻量逻辑，避免每次按键都触发昂贵计算。',
      '如果需要防抖搜索，建议使用 onFieldChange 配合 setTimeout。',
      '回车提交表单是常见模式，但要注意防止重复提交。',
    ],
    examples: [
      { title: '回车提示', code: "showMessage('按键事件已触发', 'info');" },
      { title: '回车跳转下一字段', code: "if (detail?.key === 'Enter') await focusField('nextFieldId');" },
      { title: 'ESC 清空字段', code: "if (detail?.key === 'Escape') await setValue(field, '');" },
    ],
    relatedEvents: ['onFieldPaste', 'onFieldClear'],
  }),
  createEventDoc({
    id: 'script:onFieldPaste',
    eventName: 'onFieldPaste',
    slug: 'field-paste',
    title: '字段粘贴',
    category: '行为脚本事件',
    scope: 'script',
    summary: '用户向字段中粘贴内容时触发，适合做数据清洗。',
    triggerWhen: '输入控件收到粘贴动作时触发。粘贴的内容已写入字段。',
    detailFields: [],
    tags: ['数据操作', '格式化', 'UI交互'],
    suggestions: [
      '适合做批量清洗和格式校正。',
      '粘贴后立即格式化可以提升用户体验。',
      '注意：粘贴的内容可能包含换行符和特殊字符。',
    ],
    examples: [
      { title: '去空白字符', code: "await setValue('customerCode', String(getValue('customerCode') || '').replace(/\\s+/g, ''));" },
      { title: '粘贴后转大写', code: "await setValue(field, String(value || '').toUpperCase());" },
      { title: '粘贴后格式化手机号', code: "if (field === '手机号') {\n  const phone = String(value || '').replace(/\\D/g, '');\n  await setValue('手机号', phone);\n}" },
    ],
    relatedEvents: ['onFieldChange'],
  }),
  createEventDoc({
    id: 'script:onFieldClear',
    eventName: 'onFieldClear',
    slug: 'field-clear',
    title: '字段清空',
    category: '行为脚本事件',
    scope: 'script',
    summary: '字段被显式清空时触发，适合联动清空依赖字段。',
    triggerWhen: '用户清除字段值或脚本重置该字段时触发。',
    detailFields: [],
    tags: ['联动', '状态控制', '数据操作'],
    suggestions: [
      '适合联动清空依赖字段或隐藏下游组件。',
      '清空字段后，相关的计算字段也应该同步清空。',
      '与 onFieldChange 的区别：清空是特指值变为空的情况。',
    ],
    examples: [
      { title: '联动清空备注', code: "await setValue('comment', '');" },
      { title: '清空后隐藏组件', code: "await setVisible('relatedInfo', false);" },
      { title: '清空后重置计算字段', code: "if (field === '数量' || field === '单价') {\n  await setValue('总价', 0);\n}" },
    ],
    relatedEvents: ['onFieldChange', 'onFormReset'],
  }),
  createEventDoc({
    id: 'script:onRowAdd',
    eventName: 'onRowAdd',
    slug: 'row-add',
    title: '新增行',
    category: '行为脚本事件',
    scope: 'script',
    summary: '新增一条记录或表格行时触发，适合初始化新行数据。',
    triggerWhen: '宿主向当前表单上下文增加新数据行时触发。',
    detailFields: [],
    tags: ['初始化', '数据操作', '生命周期'],
    suggestions: [
      '适合补默认字段值或标记新行状态。',
      '可以使用 nextSequence 自动生成编号。',
      '新增行后建议聚焦到第一个可编辑字段。',
    ],
    examples: [
      { title: '默认新增状态', code: "await setValue('status', '新建');" },
      { title: '新增行设置日期', code: "await setValue('createdAt', new Date().toISOString().slice(0, 10));" },
      { title: '自动生成编号', code: "const nextId = ctx.nextSequence('orders', '订单号', { start: 10001 });\nawait setValue('订单号', nextId);\nawait focusField('客户名称');" },
    ],
    relatedEvents: ['onRowDelete', 'onRowSelect'],
  }),
  createEventDoc({
    id: 'script:onRowDelete',
    eventName: 'onRowDelete',
    slug: 'row-delete',
    title: '删除行',
    category: '行为脚本事件',
    scope: 'script',
    summary: '删除当前行或某条记录时触发，适合记录审计日志。',
    triggerWhen: '宿主执行删除数据行操作后触发。此时数据已从存储中移除。',
    detailFields: [],
    tags: ['数据操作', '提示', '生命周期'],
    suggestions: [
      '适合记录日志和补充确认提示。',
      '删除后可能需要更新关联数据或统计信息。',
      '重要数据删除建议在删除前进行二次确认。',
    ],
    examples: [
      { title: '删除提示', code: "showMessage('记录已删除', 'warning');" },
      { title: '删除后打印日志', code: "PrintWarn('row deleted', field, value);" },
      { title: '删除后更新统计', code: "showMessage('记录已删除，统计数据将在下次刷新时更新', 'info');" },
    ],
    relatedEvents: ['onRowAdd', 'onRowSelect'],
  }),
  createEventDoc({
    id: 'script:onRowSelect',
    eventName: 'onRowSelect',
    slug: 'row-select',
    title: '选择行',
    category: '行为脚本事件',
    scope: 'script',
    summary: '用户选择某条记录或某一行时触发，适合联动详情面板。',
    triggerWhen: '切换当前选中行时触发。此时新行数据已加载到表单。',
    detailFields: [],
    tags: ['联动', 'UI交互', '状态控制'],
    suggestions: [
      '适合切换详情区域、加载附加说明或控制按钮可用性。',
      '可以在这里加载关联数据或更新统计信息。',
      '与 onRowLoad 的区别：选择是用户主动操作，加载可能包含系统触发。',
    ],
    examples: [
      { title: '选中提示', code: "showMessage('已切换到新记录', 'info');" },
      { title: '选中行后启用按钮', code: "await setDisabled('editBtn', false);" },
      { title: '选中行后加载关联数据', code: "const orderId = getValue('订单号');\nif (orderId) {\n  const details = ctx.findRows('订单明细', { 订单号: orderId });\n  controls.detailTable.value = details;\n}" },
    ],
    relatedEvents: ['onRowLoad'],
  }),
  createEventDoc({
    id: 'script:onDataImport',
    eventName: 'onDataImport',
    slug: 'data-import',
    title: '导入数据',
    category: '行为脚本事件',
    scope: 'script',
    summary: '导入外部数据后触发，适合做数据清洗和归一化。',
    triggerWhen: '批量导入表格或外部数据完成后触发。此时数据已写入表单。',
    detailFields: [],
    tags: ['数据操作', '格式化', '初始化'],
    suggestions: [
      '适合做批量字段修正和缺省值补齐。',
      '导入后建议提示用户复核数据。',
      '可以在这里自动计算衍生字段。',
    ],
    examples: [
      { title: '导入后提示', code: "showMessage('数据导入完成，请复核后提交', 'success');" },
      { title: '导入后补全状态', code: "if (!getValue('status')) await setValue('status', '待审核');" },
      { title: '导入后批量格式化', code: "const phone = String(getValue('手机号') || '').replace(/\\D/g, '');\nawait setValue('手机号', phone);\nconst name = String(getValue('姓名') || '').trim();\nawait setValue('姓名', name);\nshowMessage('数据已格式化', 'info');" },
    ],
    relatedEvents: ['onDataExport', 'onFormReady'],
  }),
  createEventDoc({
    id: 'script:onDataExport',
    eventName: 'onDataExport',
    slug: 'data-export',
    title: '导出数据',
    category: '行为脚本事件',
    scope: 'script',
    summary: '导出动作开始或完成时触发，适合记录审计日志。',
    triggerWhen: '宿主执行导出文件、导出记录动作时触发。',
    detailFields: [],
    tags: ['数据操作', '提示', '生命周期'],
    suggestions: [
      '适合记录导出日志、补充审计信息。',
      '可以在这里添加导出前的数据验证。',
      '导出后建议提示用户文件保存位置。',
    ],
    examples: [
      { title: '导出提示', code: "showMessage('导出任务已开始', 'info');" },
      { title: '导出后记录日志', code: "PrintInfo('data exported at', new Date().toISOString());" },
      { title: '导出前验证数据', code: "const rows = ctx.querySheet('main');\nif (rows.length === 0) {\n  showMessage('没有数据可导出', 'warning');\n  return;\n}\nshowMessage(`正在导出 ${rows.length} 条记录...`, 'info');" },
    ],
    relatedEvents: ['onDataImport', 'onSubmitSuccess'],
  }),
  createEventDoc({
    id: 'script:onValueChange',
    eventName: 'onValueChange',
    slug: 'value-change',
    title: '值变化',
    category: '行为脚本事件',
    scope: 'script',
    summary: '更偏向全局的值变化事件，用于监听表单任意值变动。',
    triggerWhen: '任意关键值变化并被宿主上报时触发。比 onFieldChange 更通用。',
    detailFields: [],
    tags: ['联动', '状态控制', '数据操作'],
    suggestions: [
      '适合做全局脏状态提示或保存草稿标记。',
      '与 onFieldChange 的区别：这里不区分具体字段，适合全局监听。',
      '频繁触发时注意性能，避免在这里做复杂计算。',
    ],
    examples: [
      { title: '标记脏状态', code: "showMessage('表单内容已变化', 'info');" },
      { title: '变化后启用保存按钮', code: "await setDisabled('saveBtn', false);" },
      { title: '自动保存草稿', code: "if (getValue('autoSave')) {\n  // 延迟保存，避免频繁触发\n  clearTimeout(window._autoSaveTimer);\n  window._autoSaveTimer = setTimeout(() => {\n    ctx.submit();\n  }, 2000);\n}" },
    ],
    relatedEvents: ['onFieldChange', 'onFormReset'],
  }),
];
