import type { BehaviorEventDocEntry } from './types';
import { createEventDoc } from './shared';

export const scriptEventDocs: BehaviorEventDocEntry[] = [
  createEventDoc({
    id: 'script:onFormLoad',
    eventName: 'onFormLoad',
    slug: 'form-load',
    title: '表单加载',
    category: '行为脚本事件',
    scope: 'script',
    summary: '表单初次装载完成后触发，适合填充默认值和初始化 UI。',
    triggerWhen: '项目测试运行或行为脚本宿主完成表单初始化后触发。',
    detailFields: [],
    tags: ['初始化', '生命周期', '默认值'],
    suggestions: ['优先在这里做默认值填充和首屏提示，不要把依赖用户输入的逻辑也塞进初始化。'],
    examples: [
      { title: '初始化默认值', code: "if (!ctx.getValue('status')) ctx.setValue('status', '草稿');" },
      { title: '设置当前日期', code: "ctx.setValue('createdAt', new Date().toISOString().slice(0, 10));" },
    ],
    relatedEvents: ['onFormReady', 'onRowLoad'],
  }),
  createEventDoc({
    id: 'script:onRowLoad',
    eventName: 'onRowLoad',
    slug: 'row-load',
    title: '数据行加载',
    category: '行为脚本事件',
    scope: 'script',
    summary: '切换到某条数据记录或重新装载当前行时触发。',
    triggerWhen: '测试运行中切换当前数据行或刷新当前行时触发。',
    detailFields: [],
    tags: ['初始化', '联动', '状态控制', '生命周期'],
    suggestions: ['适合做行级联动和状态恢复，例如根据行数据控制字段显隐。'],
    examples: [
      { title: '按行状态禁用字段', code: "ctx.setDisabled('approvalComment', ctx.getValue('status') !== '待审批');" },
      { title: '按条件隐藏组件', code: "ctx.setVisible('extraInfo', ctx.getValue('level') === '高级');" },
    ],
    relatedEvents: ['onFormLoad', 'onDataImport'],
  }),
  createEventDoc({
    id: 'script:onFieldChange',
    eventName: 'onFieldChange',
    slug: 'field-change',
    title: '字段变更',
    category: '行为脚本事件',
    scope: 'script',
    summary: '任意字段值发生变化后触发，适合做联动赋值和条件校验。',
    triggerWhen: '字段编辑完成并提交最新值后触发。',
    detailFields: [],
    tags: ['联动', '数据操作', '计算'],
    suggestions: ['把依赖单字段变化的计算放在这里；多字段提交前校验放到 onBeforeSubmit 或 onSubmit。'],
    examples: [
      { title: '同步摘要字段', code: "ctx.setValue('summary', `${ctx.getValue('customerName') || ''} / ${ctx.getValue('region') || ''}`);" },
      { title: '联动禁用字段', code: "ctx.setDisabled('endDate', !ctx.getValue('startDate'));" },
    ],
    relatedEvents: ['onValueChange', 'onFieldBlur', 'onValidate'],
  }),
  createEventDoc({
    id: 'script:onFieldBlur',
    eventName: 'onFieldBlur',
    slug: 'field-blur',
    title: '字段失焦',
    category: '行为脚本事件',
    scope: 'script',
    summary: '字段失去焦点时触发，适合做轻量校验和格式化。',
    triggerWhen: '输入焦点离开字段后触发。',
    detailFields: [],
    tags: ['校验', '格式化', 'UI交互'],
    suggestions: ['不要在这里做耗时请求；如果需要远程校验，建议先提示加载状态。'],
    examples: [
      { title: '自动去空格', code: "const value = String(ctx.getValue('customerName') || '').trim(); ctx.setValue('customerName', value);" },
      { title: '失焦校验必填', code: "if (!ctx.getValue('email')) ctx.showMessage('请输入邮箱地址', 'warning');" },
    ],
    relatedEvents: ['onFieldFocus', 'onFieldChange'],
  }),
  createEventDoc({
    id: 'script:onFieldFocus',
    eventName: 'onFieldFocus',
    slug: 'field-focus',
    title: '字段聚焦',
    category: '行为脚本事件',
    scope: 'script',
    summary: '字段获得焦点时触发，适合做辅助提示和预加载。',
    triggerWhen: '输入焦点进入某个字段时触发。',
    detailFields: [],
    tags: ['提示', 'UI交互', '预加载'],
    suggestions: ['适合展示帮助文案，不适合在这里强改用户输入。'],
    examples: [
      { title: '展示帮助', code: "ctx.showMessage('请输入完整客户名称', 'info');" },
      { title: '聚焦时滚动到顶部', code: "await ctx.scrollToField(ctx.field);" },
    ],
    relatedEvents: ['onFieldBlur'],
  }),
  createEventDoc({
    id: 'script:onButtonClick',
    eventName: 'onButtonClick',
    slug: 'button-click',
    title: '按钮点击',
    category: '行为脚本事件',
    scope: 'script',
    summary: '用户点击行为按钮时触发。',
    triggerWhen: '按钮类组件点击后触发。',
    detailFields: [],
    tags: ['提交', '数据操作', 'UI交互', '流程调用'],
    suggestions: ['适合执行提交前检查、切换页签或显式调用流程。', '如果只是同一表单内的轻量联动，优先直接使用 ctx.controls.<控件名>。'],
    examples: [
      { title: '点击后提示', code: "ctx.showMessage('按钮事件已触发', 'success');" },
      { title: '点击后把结果写进表格', code: "const rows = (await ctx.runConfiguredWorkflow()).nodeResults.get('filter')?.outputs.result || [];\nctx.controls.resultTable.value = rows;" },
    ],
    relatedEvents: ['onSubmit', 'onBeforeSubmit'],
  }),
  createEventDoc({
    id: 'script:onValidate',
    eventName: 'onValidate',
    slug: 'validate',
    title: '校验',
    category: '行为脚本事件',
    scope: 'script',
    summary: '进入表单校验阶段时触发。',
    triggerWhen: '提交前或显式调用校验时触发。',
    detailFields: [],
    tags: ['校验', '提示', '提交'],
    suggestions: ['在这里收口跨字段校验逻辑，并用 showMessage 明确给出失败原因。'],
    examples: [
      { title: '校验开始日期', code: "if (!ctx.getValue('startDate')) ctx.showMessage('请选择开始日期', 'warning');" },
      { title: '校验日期范围', code: "const start = ctx.getValue('startDate');\nconst end = ctx.getValue('endDate');\nif (start && end && start > end) ctx.showMessage('结束日期不能早于开始日期', 'error');" },
    ],
    relatedEvents: ['onBeforeSubmit', 'onSubmit', 'onSubmitError'],
  }),
  createEventDoc({
    id: 'script:onSubmit',
    eventName: 'onSubmit',
    slug: 'submit',
    title: '提交',
    category: '行为脚本事件',
    scope: 'script',
    summary: '用户触发提交动作时执行，适合做最终校验和收口动作。',
    triggerWhen: '点击提交或调用 ctx.submit() 后触发。',
    detailFields: [],
    tags: ['提交', '数据操作', '生命周期'],
    suggestions: ['把不可逆的副作用集中放在这里，避免字段级事件重复触发。'],
    examples: [
      { title: '提交前补全时间', code: "ctx.setValue('submittedAt', new Date().toISOString());" },
      { title: '提交前补全状态', code: "if (!ctx.getValue('status')) ctx.setValue('status', '待审核');" },
    ],
    relatedEvents: ['onBeforeSubmit', 'onSubmitSuccess', 'onSubmitError'],
  }),
  createEventDoc({
    id: 'script:onSubmitSuccess',
    eventName: 'onSubmitSuccess',
    slug: 'submit-success',
    title: '提交成功',
    category: '行为脚本事件',
    scope: 'script',
    summary: '提交成功后触发，适合清理状态和反馈提示。',
    triggerWhen: '提交流程成功完成后触发。',
    detailFields: [],
    tags: ['提交', '提示', '状态控制', '生命周期'],
    suggestions: ['适合做跳转、清空临时字段和成功提示。'],
    examples: [
      { title: '成功提示', code: "ctx.showMessage('提交成功', 'success');" },
      { title: '清空草稿字段', code: "ctx.clearValues(['draft', 'tempNote']);" },
    ],
    relatedEvents: ['onSubmit', 'onSubmitError'],
  }),
  createEventDoc({
    id: 'script:onSubmitError',
    eventName: 'onSubmitError',
    slug: 'submit-error',
    title: '提交失败',
    category: '行为脚本事件',
    scope: 'script',
    summary: '提交失败后触发，适合记录错误和指导用户修正。',
    triggerWhen: '提交流程抛错或返回失败状态后触发。',
    detailFields: [],
    tags: ['提交', '提示', '校验'],
    suggestions: ['这里更适合兜底提示，不要再尝试自动重复提交。'],
    examples: [
      { title: '失败提示', code: "ctx.showMessage('提交失败，请检查必填项', 'error');" },
      { title: '滚动到首个错误字段', code: "await ctx.scrollToField('customerName');" },
    ],
    relatedEvents: ['onSubmit', 'onValidate'],
  }),
  createEventDoc({
    id: 'script:onFormReady',
    eventName: 'onFormReady',
    slug: 'form-ready',
    title: '表单就绪',
    category: '行为脚本事件',
    scope: 'script',
    summary: '表单和依赖数据全部准备完成后触发。',
    triggerWhen: '首屏数据与组件都可交互时触发。',
    detailFields: [],
    tags: ['初始化', '生命周期', '提示'],
    suggestions: ['适合做依赖异步数据的初始化，而不是 onFormLoad 里的同步准备。'],
    examples: [
      { title: '就绪提示', code: "ctx.showMessage('表单已准备就绪', 'info');" },
      { title: '就绪后聚焦首字段', code: "await ctx.focusField('customerName');" },
    ],
    relatedEvents: ['onFormLoad', 'onDataImport'],
  }),
  createEventDoc({
    id: 'script:onFormReset',
    eventName: 'onFormReset',
    slug: 'form-reset',
    title: '表单重置',
    category: '行为脚本事件',
    scope: 'script',
    summary: '表单被重置时触发。',
    triggerWhen: '用户执行重置动作或宿主恢复初始值时触发。',
    detailFields: [],
    tags: ['状态控制', '生命周期', 'UI交互'],
    suggestions: ['适合恢复依赖值和提示用户，不要在这里再写回大量默认值。'],
    examples: [
      { title: '重置提示', code: "ctx.showMessage('表单已恢复初始值', 'info');" },
      { title: '重置后重新启用字段', code: "await ctx.setFieldState('comment', { disabled: false, visible: true });" },
    ],
    relatedEvents: ['onFormLoad', 'onValueChange'],
  }),
  createEventDoc({
    id: 'script:onBeforeSubmit',
    eventName: 'onBeforeSubmit',
    slug: 'before-submit',
    title: '提交前',
    category: '行为脚本事件',
    scope: 'script',
    summary: '真正提交前的最后一道钩子，适合做最后检查和参数整理。',
    triggerWhen: '进入提交动作，但尚未发出最终提交请求前触发。',
    detailFields: [],
    tags: ['提交', '数据操作', '校验'],
    suggestions: ['这里适合整理提交 payload，而不是做大量 UI 联动。'],
    examples: [
      { title: '补全审批人', code: "if (!ctx.getValue('reviewer')) ctx.setValue('reviewer', '系统默认审批人');" },
      { title: '校验后阻止提交', code: "if (!ctx.getValue('agree')) { ctx.showMessage('请先勾选同意协议', 'error'); return; }" },
    ],
    relatedEvents: ['onValidate', 'onSubmit'],
  }),
  createEventDoc({
    id: 'script:onFieldKeyDown',
    eventName: 'onFieldKeyDown',
    slug: 'field-key-down',
    title: '字段按键',
    category: '行为脚本事件',
    scope: 'script',
    summary: '字段按键时触发，适合快捷键响应。',
    triggerWhen: '输入控件收到键盘按下事件时触发。',
    detailFields: [],
    tags: ['UI交互', '快捷键', '数据操作'],
    suggestions: ['只放轻量逻辑，避免每次按键都触发昂贵计算。'],
    examples: [
      { title: '回车提示', code: "ctx.showMessage('按键事件已触发', 'info');" },
      { title: '回车跳转下一字段', code: "if (ctx.detail?.key === 'Enter') await ctx.focusField('nextFieldId');" },
    ],
    relatedEvents: ['onFieldPaste', 'onFieldClear'],
  }),
  createEventDoc({
    id: 'script:onFieldPaste',
    eventName: 'onFieldPaste',
    slug: 'field-paste',
    title: '字段粘贴',
    category: '行为脚本事件',
    scope: 'script',
    summary: '用户向字段中粘贴内容时触发。',
    triggerWhen: '输入控件收到粘贴动作时触发。',
    detailFields: [],
    tags: ['数据操作', '格式化', 'UI交互'],
    suggestions: ['适合做批量清洗和格式校正。'],
    examples: [
      { title: '去空白字符', code: "ctx.setValue('customerCode', String(ctx.getValue('customerCode') || '').replace(/\\s+/g, ''));" },
      { title: '粘贴后转大写', code: "ctx.setValue(ctx.field, String(ctx.value || '').toUpperCase());" },
    ],
    relatedEvents: ['onFieldChange'],
  }),
  createEventDoc({
    id: 'script:onFieldClear',
    eventName: 'onFieldClear',
    slug: 'field-clear',
    title: '字段清空',
    category: '行为脚本事件',
    scope: 'script',
    summary: '字段被显式清空时触发。',
    triggerWhen: '用户清除字段值或脚本重置该字段时触发。',
    detailFields: [],
    tags: ['联动', '状态控制', '数据操作'],
    suggestions: ['适合联动清空依赖字段或隐藏下游组件。'],
    examples: [
      { title: '联动清空备注', code: "ctx.setValue('comment', '');" },
      { title: '清空后隐藏组件', code: "await ctx.setVisible('relatedInfo', false);" },
    ],
    relatedEvents: ['onFieldChange', 'onFormReset'],
  }),
  createEventDoc({
    id: 'script:onRowAdd',
    eventName: 'onRowAdd',
    slug: 'row-add',
    title: '新增行',
    category: '行为脚本事件',
    scope: 'script',
    summary: '新增一条记录或表格行时触发。',
    triggerWhen: '宿主向当前表单上下文增加新数据行时触发。',
    detailFields: [],
    tags: ['初始化', '数据操作', '生命周期'],
    suggestions: ['适合补默认字段值或标记新行状态。'],
    examples: [
      { title: '默认新增状态', code: "ctx.setValue('status', '新建');" },
      { title: '新增行设置日期', code: "ctx.setValue('createdAt', new Date().toISOString().slice(0, 10));" },
    ],
    relatedEvents: ['onRowDelete', 'onRowSelect'],
  }),
  createEventDoc({
    id: 'script:onRowDelete',
    eventName: 'onRowDelete',
    slug: 'row-delete',
    title: '删除行',
    category: '行为脚本事件',
    scope: 'script',
    summary: '删除当前行或某条记录时触发。',
    triggerWhen: '宿主执行删除数据行操作后触发。',
    detailFields: [],
    tags: ['数据操作', '提示', '生命周期'],
    suggestions: ['适合记录日志和补充确认提示。'],
    examples: [
      { title: '删除提示', code: "ctx.showMessage('记录已删除', 'warning');" },
      { title: '删除后打印日志', code: "ctx.console.log('row deleted', ctx.field, ctx.value);" },
    ],
    relatedEvents: ['onRowAdd', 'onRowSelect'],
  }),
  createEventDoc({
    id: 'script:onRowSelect',
    eventName: 'onRowSelect',
    slug: 'row-select',
    title: '选择行',
    category: '行为脚本事件',
    scope: 'script',
    summary: '用户选择某条记录或某一行时触发。',
    triggerWhen: '切换当前选中行时触发。',
    detailFields: [],
    tags: ['联动', 'UI交互', '状态控制'],
    suggestions: ['适合切换详情区域、加载附加说明或控制按钮可用性。'],
    examples: [
      { title: '选中提示', code: "ctx.showMessage('已切换到新记录', 'info');" },
      { title: '选中行后启用按钮', code: "await ctx.setDisabled('editBtn', false);" },
    ],
    relatedEvents: ['onRowLoad'],
  }),
  createEventDoc({
    id: 'script:onDataImport',
    eventName: 'onDataImport',
    slug: 'data-import',
    title: '导入数据',
    category: '行为脚本事件',
    scope: 'script',
    summary: '导入外部数据后触发，适合做归一化处理。',
    triggerWhen: '批量导入表格或外部数据完成后触发。',
    detailFields: [],
    tags: ['数据操作', '格式化', '初始化'],
    suggestions: ['适合做批量字段修正和缺省值补齐。'],
    examples: [
      { title: '导入后提示', code: "ctx.showMessage('数据导入完成，请复核后提交', 'success');" },
      { title: '导入后补全状态', code: "if (!ctx.getValue('status')) ctx.setValue('status', '待审核');" },
    ],
    relatedEvents: ['onDataExport', 'onFormReady'],
  }),
  createEventDoc({
    id: 'script:onDataExport',
    eventName: 'onDataExport',
    slug: 'data-export',
    title: '导出数据',
    category: '行为脚本事件',
    scope: 'script',
    summary: '导出动作开始或完成时触发。',
    triggerWhen: '宿主执行导出文件、导出记录动作时触发。',
    detailFields: [],
    tags: ['数据操作', '提示', '生命周期'],
    suggestions: ['适合记录导出日志、补充审计信息。'],
    examples: [
      { title: '导出提示', code: "ctx.showMessage('导出任务已开始', 'info');" },
      { title: '导出后记录日志', code: "ctx.console.log('data exported at', new Date().toISOString());" },
    ],
    relatedEvents: ['onDataImport', 'onSubmitSuccess'],
  }),
  createEventDoc({
    id: 'script:onValueChange',
    eventName: 'onValueChange',
    slug: 'value-change',
    title: '值变化',
    category: '行为脚本事件',
    scope: 'script',
    summary: '更偏向全局的值变化事件，用于监听表单任意值变动。',
    triggerWhen: '任意关键值变化并被宿主上报时触发。',
    detailFields: [],
    tags: ['联动', '状态控制', '数据操作'],
    suggestions: ['适合做全局脏状态提示或保存草稿标记。'],
    examples: [
      { title: '标记脏状态', code: "ctx.showMessage('表单内容已变化', 'info');" },
      { title: '变化后启用保存按钮', code: "await ctx.setDisabled('saveBtn', false);" },
    ],
    relatedEvents: ['onFieldChange', 'onFormReset'],
  }),
];
