/** Chinese-language parameter documentation for all FormFlow tool parameters. */
export const FIELD_DESCRIPTIONS: Record<string, string> = {
  projectId: '目标项目的稳定 ID。省略仅在调用上下文已经唯一绑定项目且该字段非必填时有效。',
  baseRevision: '最近一次 project.get 返回的 revision。服务端仅在它仍是最新版本时执行写入，否则拒绝且不修改项目。',
  idempotencyKey: '本次写操作的稳定幂等键。重试同一意图必须复用；新的业务操作必须生成新键。',
  confirmationToken: '仅在首次返回 confirmation_required 后填写；必须保持其他业务参数完全不变。令牌一次性且会过期。',
  id: '当前工具目标资源的稳定 ID；创建时成为新资源 ID，读取、更新或删除时用于精确定位现有资源。',
  name: '面向用户显示的名称；不作为稳定引用 ID。',
  description: '面向用户显示的项目或资源说明。',
  author: '项目元数据中的作者名称；不改变访问权限或所有者。',
  tags: '用于项目检索和分类的标签列表。',
  newId: '克隆后新项目的稳定 ID；不会修改原项目。',
  type: '目标类型的稳定标识。可用值应先从对应 catalog 工具读取。',
  category: '可选的目录分类过滤条件；省略时返回全部分类。',
  templateId: '操作或项目模板的稳定 ID；先从对应模板目录读取，不要猜测。',
  templateIds: '要处理的模板稳定 ID 列表；只影响明确列出的模板。',
  tableId: '目标数据源/表的稳定 ID。',
  tableIds: '参与本次操作的数据源/表稳定 ID 列表。',
  sheetName: '目标数据源内的 Sheet 名称；必须与现有名称完全一致。',
  formId: '目标表单的稳定 ID。',
  workflowId: '目标工作流的稳定 ID。',
  relationId: '目标数据关系的稳定 ID。',
  relationIds: '参与本次操作的数据关系稳定 ID 列表。',
  relation: '完整的数据关系定义；明确指定两端表、Sheet、连接字段与关系类型，校验或保存后按 relation.id 引用。',
  suiteId: '要运行的已保存回归套件 ID；省略时按工具说明使用默认套件。',
  fieldName: '目标字段名；必须与目标 Sheet 或结果中的字段名完全一致。',
  fields: '明确选择的字段名列表；未列出的字段不参与本次操作。',
  keyFields: '组合主键字段列表；按给定顺序共同标识唯一数据行。',
  scope: '行为作用域：global 影响整个项目，sheet 仅影响指定 Sheet，form 仅影响指定表单。',
  mode: '操作模式。仅接受 schema enum 中列出的值；不同值会产生不同运行或编辑结果。',
  joinType: '数据关系查询的连接方式；决定未匹配记录是否保留。',
  fileId: '通过上传接口获得的暂存文件 ID；不是服务器文件路径或远程 URL。',
  csv: '内联 CSV 文本。与 fileId、rows 互斥，作为本次导入的唯一数据内容。',
  rows: '内联业务记录数组。与 fileId、csv 互斥；每个对象是一条记录。',
  rowCount: '要生成的数据行数；不会改变现有行，除非调用的是明确的 apply 工具。',
  adds: '要新增的完整业务记录；成功后追加到目标 Sheet。',
  updates: '按稳定 rowKey 定位的字段变更；未列出的字段保持不变。',
  deletes: '要删除的稳定 rowKey 列表；非空时执行前需要确认。',
  operations: '按顺序原子执行的数据变更列表；任一项失败时整体不提交。',
  patch: '局部更新对象；仅其中明确出现且允许修改的字段会被覆盖。',
  config: '目标资源配置。具体允许字段、默认值与限制见此对象的子 schema。',
  settings: '项目设置的局部更新；未提供的设置保持不变。',
  design: '完整或新建表单设计对象；不会自动修改行为规则代码。',
  item: '要创建、替换或局部合并的资源对象；其稳定 ID 决定新增还是更新。',
  behavior: '完整的结构化行为定义；成功后在指定 scope 内按 behavior.id 保存。',
  code: '要检查、测试或保存的规则代码；保存前必须通过对应语法检查。',
  dataSource: '用于一次构建项目的数据源定义；导入规则与 data_source.create 相同。',
  forms: '从数据源生成的表单定义列表；省略时创建 create、edit 和 detail 三个表单。',
  selection: '模板或分析明确选中的表、关系和字段；只对列出的资源生成计划。',
  parameters: '模板或分析参数；允许字段与默认值由所选模板的 parameterSchema 决定。',
  plan: '由 template.plan 返回且尚未应用的原始计划；不得手工改写，其 baseRevision 必须与提交版本一致。',
  preset: '要保存的模板参数预设；只保存参数，不保存业务数据选择。',
  package: '待导入的纯声明模板包；校验通过后才写入项目。',
  overwrite: '为 true 时允许覆盖同名目标，并在执行前要求确认；false 时遇到冲突会失败且不修改。',
  overwriteModified: '为 true 时允许覆盖检测到的手工修改，并在执行前要求确认；false 时保留手工修改并阻止覆盖。',
  cascade: '为 true 时同时处理明确报告的下游引用，并在执行前要求确认；false 时存在引用会拒绝且不修改。',
  page: '从 1 开始的结果页码。',
  pageSize: '每页返回数量；服务端会限制到 schema 或能力目录声明的最大值。',
  baseVersion: '最近一次数据查询返回的 dataVersion。数据已变化时拒绝整批写入，避免覆盖并发修改。',
  keySearch: '按主键字段精确匹配的键值对象；与全文 search 同时提供时两种条件共同生效。',
  search: '可选的全文搜索文本；省略或为空时不应用全文过滤。',
  query: '只读搜索关键词；不会修改项目。',
  sortModel: '排序规则列表；按数组顺序确定多字段排序优先级。',
  filterModel: '字段过滤条件对象；只影响本次查询结果。',
  exportAll: '为 true 时返回全部匹配结果而非当前分页；仍不修改项目。',
  runtime: '用于只读规则或表单检查的运行时快照；敏感字段会脱敏返回。',
  seed: '确定性生成随机种子；相同输入与 seed 产生相同候选数据。',
  scenarios: '要包含的测试或 Mock 场景列表；负向场景不会写入业务数据。',
};
